// Help: one screen of every control, grouped by where you are.

import { Game, Scene, VW, VH } from "../game";
import { drawText, textWidth } from "../gfx/font";
import { PAL } from "../gfx/palette";

const SECTIONS: [string, string[]][] = [
  ["FLIGHT", [
    "W/S THRUST  A/D TURN  X BRAKE  J CRUISE  N AUTOPILOT (FLIES YOUR PLOTTED COURSE)",
    "MOUSE AIMS THE TURRET: LEFT-CLICK FIRE, RIGHT-CLICK MINE  (SPACE / M IN KEYBOARD MODE)",
    "R TORPEDO  C SEISMIC CHARGE (CORE ROCKS)  V HOLD: DEEP SCAN + LOG THE SYSTEM",
    "E DOCK / JUMP / ORBIT / BOARD / TEND  T HAIL  L LOG  TAB MAP  G GALAXY  I SHIP  ESC PAUSE",
  ]],
  ["HELPING SHIPS", ["E NEAR A STRICKEN FREIGHTER: BOARD AND REPAIR IT (HOLD E PER SYSTEM), SEND YOUR ENGINEER,",
    "TOW IT IN (SLOW, NO JUMPS), TAKE SURVIVORS ABOARD, OR PASS A SPARE PART. CRISES PAY 2.5X."]],
  ["OTHER PILOTS", ["T SYSTEM CHANNEL  /GIVE <QTY> <GOODS> <CALLSIGN>  /PAY <CREDITS> <CALLSIGN>  (WITHIN 300M)",
    "/S <MESSAGE> TALKS ON YOUR SQUADRON CHANNEL ANYWHERE  KILLS NEAR A WINGMATE ARE SHARED"]],
  ["GALAXY MAP", ["CLICK A SYSTEM FOR INTEL  CLICK AGAIN OR N TO PLOT A COURSE  B BOOKMARK  V LAYERS"]],
  ["ORBIT", ["ARROWS / CLICK: TARGET A SITE  E LAND THERE  L DROP THE ROVER IN ITS REGION  V HOLD: SURVEY"]],
  ["GROUNDSIDE", ["WASD DRIVE  E MINE / SALVAGE / ENTER A SITE / LIFT OFF AT THE LANDER",
    "V HOLD: SCAN FLORA  R PATCH THE ROVER AT THE LANDER (SPARE PARTS)  H STAKE OR WORK A CLAIM"]],
  ["STATIONS", [
    "ARROWS / CLICK  ENTER SELLS WHAT YOU HOLD, ELSE BUYS  B / RIGHT-CLICK BUY  S SELL",
    "SHIFT TRADES IN BULK  P WALK THE DECK  ESC UNDOCK  BAR: HIRE CREW AND TAKE FARES",
    "SHIPS: ENTER BUYS WITH TRADE-IN, K BUYS AND PARKS THE OLD HULL, N NAMES IT, O PAINTS IT",
    "SURVEY SELLS EXPLORATION DATA  ENGINEER (RESEARCH / REFINERY POSTS) SPENDS MATERIALS",
    "RECORD: RANKS AND DEEDS (L: LOG)  SURVEY: DATA (C: CODEX)  MISSIONS: DAILY + WEEKLY GOALS",
    "MARKET: I STAKE  NEWS: Y/N VOTE  SHIPS: L LINER TO A PARKED HULL  RECORD: P GUESTBOOK",
    "BAR: R ROSTER, LAST ROW ENTERS THE RING RACE  RACE RINGS APPEAR WHEN YOU LAUNCH",
  ]],
  ["ON FOOT", ["WASD WALK  E USE (HOLD TO FIX THINGS)  R ROSTER  V LOOK OUT  C CARDS  COMMS PANEL: THE BAND"]],
  ["EVERYWHERE", ["F5 SAVE  F9 LOAD  F7 POSTCARD  H MUSIC  F FULLSCREEN  ESC BACK  FLIGHT KEYS CAN BE REBOUND", "SAVE SLOTS ON THE TITLE SCREEN: THREE LOCAL GAMES, EACH WITH ITS OWN CLOUD CODE"]],
];

export class HelpScene implements Scene {
  touchMode = "menu" as const;
  update(g: Game, dt: number): void {
    void dt;
    if (g.input.wasPressed("Escape") || g.input.wasPressed("Enter") || g.input.mousePressed) g.setScene("title");
  }
  draw(g: Game, ctx: CanvasRenderingContext2D): void {
    void g;
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, VH);
    drawText(ctx, "CONTROLS", 12, 8, PAL.white);
    drawText(ctx, "ESC BACK", VW - textWidth("ESC BACK") - 12, 8, PAL.greyDark);
    let y = 22;
    for (const [title, lines] of SECTIONS) {
      drawText(ctx, title, 12, y, PAL.ui); y += 8;
      for (const l of lines) { drawText(ctx, l, 12, y, PAL.grey); y += 7; }
      y += 3;
    }
  }
}
