// What's new: a short changelog for returning pilots, reachable from the title.

import { Game, Scene, VW, VH } from "../game";
import { drawText, textWidth } from "../gfx/font";
import { PAL } from "../gfx/palette";

const NOTES: [string, string[]][] = [
  ["0.66 - A NAME ON THE LANES", [
    "DO ONE THING MORE THAN ANYTHING ELSE AND THE LANES NAME YOU FOR IT. CONTROL, FRIENDS, THE CROWD AND THE CREW ALL USE IT.",
  ]],
  ["0.65 - RITES OF PASSAGE", [
    "A WEDDING ON THE BRIDGE, A BIRTH ON YOUR DECK, A PASSING BY THE VIEWPORT, AND TWO OF YOUR OWN ASKING YOU TO DO THE HONOURS.",
  ]],
  ["0.64 - THE POST", [
    "EVERY CIVIL STATION HAS A MAIL BAG FOR THE NEXT SHIP OUT. NO HOLD SPACE, SMALL PAY, AND SOMETIMES A LETTER IS FOR YOU.",
  ]],
  ["0.63 - WINDOWS AND BAYS", [
    "V ABOARD: LOOK OUT OF YOUR OWN SHIP. YOUR SHIP AND YOUR PARKED HULLS SIT IN THE PROMENADE BAYS.",
  ]],
  ["0.62 - THE COURSE RECORD", [
    "EVERY RING COURSE HAS A RECORD HOLDER. BEAT THEM AND THE BAR HEARS. IN THE REAL GALAXY YOUR TIMES GO TO THE WIRE.",
  ]],
  ["0.61 - WATCHES", [
    "HALF THE CREW ON WATCH AT THEIR POSTS, HALF OFF. PASSENGERS WALK THE DECK AND QUESTION THE CREW, WHO ANSWER IN CHARACTER.",
  ]],
  ["0.60 - THE RING RACE", [
    "ENTER FROM ANY LOUNGE, LAUNCH, AND FLY SIX RINGS ROUND THE STATION AGAINST THE CLOCK. PRIZE MONEY, PAR, YOUR BEST TIME.",
  ]],
  ["0.59 - CONCOURSE GOSSIP", [
    "THE CROWD ON A STATION PROMENADE TALK ABOUT THE WORLD, AND ABOUT YOU. STAND CLOSE AND LISTEN.",
  ]],
  ["0.58 - CORRIDOR TALK", [
    "THE CREW TALK TO EACH OTHER ABOARD, WALK THE DECK DOOR TO DOOR, AND GATHER AT THE GALLEY AT MESS CALL. EAT WITH THEM.",
  ]],
  ["0.57 - ENCOUNTERS", [
    "TEN NEW CARDS ON THE LANES AND THE GROUND, NONE OF THEM FIGHTS: A BUOY, A LOST DRONE, A BIRTHDAY, A HOT POOL, AND MORE.",
  ]],
  ["0.56 - THE ROSTER", [
    "R ABOARD OR IN THE LOUNGE: THE WHOLE CREW ON ONE PAGE, WITH MORALE, LOYALTY, SKILL PROGRESS AND A BONUS ON ENTER.",
  ]],
  ["0.55 - ODDS AND ENDS", [
    "EACH HULL CLASS HAS ITS OWN VOICE. RETIREMENTS REACH THE WIRE. THE GALAXY MAP HAS A LEGEND.",
  ]],
  ["0.54 - REGULARS", [
    "STATIONS COUNT YOUR DOCKINGS. BULLETINS MENTION YOU, PASSENGERS LEAVE REVIEWS, THE YARD GIVES REGULARS A RATE.",
  ]],
  ["0.53 - PASSENGERS UNDERFOOT", [
    "PASSENGERS STRETCH THEIR LEGS ABOARD: THE SEAT, THE GALLEY, THE BRIDGE. TALK TO WHOEVER YOU'RE BESIDE.",
  ]],
  ["0.52 - LORE", [
    "EVERY SYSTEM AND EVERY WORLD HAS A LINE OF HISTORY NOW. THE CHART READS IT ON ARRIVAL.",
  ]],
  ["0.51 - MORE OF EVERYTHING", [
    "TEN SERIALS, TWENTY-FOUR ENCOUNTERS, NINE KINDS OF WONDER, MORE TRAITS, A HAMMOCK AND A MURAL FOR THE DECK.",
  ]],
  ["0.50 - THE CHRONICLE ROOM", [
    "READ YOUR WHOLE CHRONICLE IN-GAME: C ON THE RECORD TAB, THE TITLE SCREEN, OR THE PAUSE MENU.",
  ]],
  ["0.49 - MUSIC AND SLOTS", [
    "THE HUM CHANGES FOR YOUR WAYSTATION, THE ARK AND THE WONDERS. SAVE SLOTS TELL THE STORY SO FAR.",
  ]],
  ["0.48 - OTHER KEEPERS", [
    "IN THE REAL GALAXY, LIGHTS OTHER PILOTS HAVE PLANTED SHOW ON YOUR CHART. YOURS SHOW ON THEIRS.",
  ]],
  ["0.47 - COMFORT", [
    "SETTINGS FOR THE COMMS BAND AND THE SHIP'S VOICE. V HIDES THE GALAXY MAP OVERLAYS. TOUCH GETS PAUSE AND LOG.",
  ]],
  ["0.46 - SMALL KINDNESSES", [
    "THE CROSSING RETURNS TO A KEPT LIGHT. THE CAT BRINGS THINGS UP FROM THE HOLD. THE WALL KEEPS ALL THREE CAMPAIGNS.",
  ]],
  ["0.45 - THE LEDGER", [
    "B ON THE RECORD TAB: WHERE THE MONEY CAME FROM AND WHERE IT WENT, LIFETIME, BY SOURCE.",
  ]],
  ["0.44 - COMPANY", [
    "CREW WALK THE DECK. PASSENGERS ASK FOR DETOURS TO WONDERS FOR 40% MORE. OLD SHIPMATES WRITE.",
  ]],
  ["0.43 - PLACES WITH DETAIL", [
    "CRATES IN THE HOLD, CREW BELONGINGS BY THEIR BUNKS, LUGGAGE BY THE SEAT, PROMENADES DRESSED FOR THEIR TRADE.",
  ]],
  ["0.42 - TOWN PROJECTS", [
    "A TOWN'S FOREMAN TAKES FUNDING: A SCHOOL, A CLINIC, A SECOND PAD, A CHAPEL. GROWTH, EFFECTS, AND A BUILDING TO SEE.",
  ]],
  ["0.41 - THE KEEPER", [
    "A THIRD CAMPAIGN: A DYING LIGHTHOUSE, ITS KEEPER'S LOG, WHAT THE LIGHT SAW, AND WHOSE LIGHT IT IS.",
  ]],
  ["0.40 - QUIET MOMENTS", [
    "ESC IN FLIGHT PAUSES THE GALAXY: SAVE, SETTINGS, THE HANDBOOK, OR HOME. PULSARS TICK; THE CATHEDRAL HUMS.",
  ]],
  ["0.39 - FACES", [
    "A SENATOR, AN HEIR AND A SINGER WANT SHIPS NOW AND THEN. LAND THEM HAPPY OR SOUR AND THE GALAXY HEARS.",
    "THE PROMENADE CROWD MATCHES THE DAY: STALLS, MOURNERS, PICKETS, REVELLERS.",
  ]],
  ["0.38 - CREW ARCS", [
    "CREW WHO TRUST YOU ASK FOR SOMETHING BIGGER: THEIR OWN STORY, THREE BEATS LONG, ADVANCED BY REAL PLAY.",
  ]],
  ["0.37 - SHARED SKY", [
    "IN THE REAL GALAXY, THE FIRST PILOT TO LOG A WONDER PUTS THEIR NAME ON EVERYONE'S CHART. L OPENS THE COMMS LOG.",
  ]],
  ["0.36 - SECOND HOUR", [
    "FLIGHT SCHOOL HAS THREE MORE LESSONS: THE LOUNGE, THE PROMENADE, A FARE OR A RESCUE. THE CAT PURRS. LETTERS CHIME.",
  ]],
  ["0.35 - RHYTHMS", [
    "THE WEEK HAS A SHAPE: FOUNDERS' DAY, THE LONG SILENCE, LANTERN NIGHT, MARKET DAY, REMEMBRANCE, YARD DAY, OPEN LANES.",
    "USED HULLS CARRY A HISTORY. A LIT BEACON EASES PIRACY IN ITS SYSTEM.",
  ]],
  ["0.34 - BELONGING", [
    "ASK A FRIEND IN THE LOUNGE TO RIDE ALONG. CALL A STATION HOME. DONATE RELICS TO A MUSEUM WITH YOUR NAME UNDER THE GLASS.",
  ]],
  ["0.33 - RIVALS", [
    "ONE OF THE REGULARS HAS IT IN FOR YOU: FARES TAKEN, SIGHTS LOGGED FIRST, ROUTES UNDERCUT. HELP THEM TWICE TO END IT.",
    "A HARBOURMASTER'S OFFICE ON THE PROMENADE KNOWS THE LANES, YOUR BERTH LOG AND YOUR CHARTERS.",
  ]],
  ["0.32 - HANDBOOK AND VOICE", [
    "A HANDBOOK ON THE TITLE SCREEN. THE SHIP SPEAKS ON THE BAND NOW AND THEN. A GREENHOUSE GROWS PROVISIONS.",
  ]],
  ["0.31 - THE WAYSTATION", [
    "TURN A LIT BEACON OR DEPOT INTO A WAYSTATION OF YOUR OWN: A TILL, A BAR THE REGULARS DRINK AT, A BUNK.",
  ]],
  ["0.30 - CONTACTS", [
    "THE LANES HAVE REGULARS. HELP ONE TWICE AND THEY'RE A FRIEND: HAILS, A SEAT IN THE LOUNGE, LETTERS WITH GIFTS.",
  ]],
  ["0.29 - APPROACH AND LAUNCH", [
    "DOCKING IS AN APPROACH NOW: CONTROL CLEARS A BAY AND THE SHIP GLIDES IN. LAUNCHES TOO. THE ARK CAN BE BOARDED.",
  ]],
  ["0.28 - WONDERS", [
    "EVERY GALAXY HAS LANDMARKS NOW: A RING, A PULSAR, AN ARK, A GLASS BELT, TWIN STARS. RUMOURS IN THE BARS POINT THE WAY.",
  ]],
  ["0.27 - CHARTERS", [
    "CHARTER A HAULER AT ANY SHIPYARD TO RUN YOUR BEST KNOWN ROUTE WHILE YOU FLY. 60% OF THE MARGIN IS YOURS.",
  ]],
  ["0.26 - SETTLEMENTS GROW", [
    "OUTPOSTS GROW ON YOUR TRADE AND WORK: 100 MAKES A TOWN, 250 A CITY, WITH YOUR NAME ON THE PLAQUE.",
  ]],
  ["0.25 - SHIPMATES", [
    "CREW MAKE FRIENDS AND ENEMIES. FEUDS DRAG MORALE DOWN UNTIL YOU SIT THEM DOWN WITH A BOTTLE.",
    "A CLINIC ON THE PROMENADE. X ON THE RECORD TAB EXPORTS YOUR WHOLE CHRONICLE AS TEXT.",
  ]],
  ["0.24 - KEEPSAKES", [
    "F7 TAKES A POSTCARD. FURNISH THE DECK AT ANY SHIPYARD: A PLANT, A RUG, A JUKEBOX, A VIEWPORT, A SHELF.",
    "THE LANES REMEMBER: THE COMMS BAND TALKS ABOUT YOUR SHIP BY NAME ONCE IT HAS EARNED IT.",
  ]],
  ["0.23 - SERIALS", [
    "GALNET RUNS SERIALS NOW: STORIES IN PARTS, KEPT ON THE NEWS TAB, ENDING IN A CONTRACT, A PREMIUM OR A RECRUIT.",
  ]],
  ["0.22 - LIFE ON THE DECK", [
    "CREW LEARN BY DOING: REPAIRS, KILLS, JUMPS AND PATIENTS COUNT TOWARD THE NEXT SKILL.",
    "REST A WHILE AT ANY SHIPYARD. A SHIP'S CAT FROM THE HOLD OR AN AGRI YARD. ION STORMS THAT BEACONS SEE THROUGH.",
  ]],
  ["0.21 - LEGACY", [
    "RETIRE THE CAPTAIN AT THE WALL OF RECORD. A CREW MEMBER TAKES THE CHAIR, OR THE YARD FINDS A NEW NAME.",
    "THE SHIP, ITS WALL, ITS CREW, YOUR STRUCTURES AND EVERYONE YOU FLEW WITH STAY. THE OLD CAPTAIN WALKS THE PROMENADE.",
  ]],
  ["0.20 - THE LIGHTHOUSE", [
    "SQUADRON TREATIES ON THE BASE TAB: PACTS SIGNED BY BOTH SIDES, RIVALRIES DECLARED BY ONE.",
    "SIX MORE ENCOUNTERS. THE TITLE SCREEN TELLS THE STORY SO FAR. THE SHIPS TAB SHOWS YOUR PAINT.",
    "WALK THE DECK AND MEET YOUR OWN PEOPLE: CREW ON LEAVE AND SHIPMATES WHO RETIRED HERE.",
    "BEACON AND FUEL DEPOT KITS AT ANY SHIPYARD. PLANT THEM IN A DEAD SYSTEM WITH E.",
    "BEACONS PULL TRAFFIC AND COLLECT TOLLS; JUMPS THROUGH A LIT SYSTEM COST A FIFTH LESS. DEPOTS SELL YOUR FUEL.",
    "RAIDERS WEAR STRUCTURES DOWN. BRING SPARE PARTS, EMPTY THE TILL, KEEP THE LIGHT ON.",
  ]],
  ["0.19 - THE LINER TRADE", [
    "FARES WAIT IN EVERY STATION LOUNGE: VIPS, TOURISTS, REFUGEES, COURIERS, FUGITIVES. CABINS CARRY THREE.",
    "PASSENGERS HAVE MOODS. BRING WHAT THEY ASK FOR, KEEP THE HULL WHOLE, DON'T DAWDLE. PAY RUNS 60-120%.",
    "TOURISTS BOOK A SIGHT: A WORLD, THE DRIFTERS, A COMET, A FESTIVAL. EVERY EXTRA SIGHT PAYS MORE.",
  ]],
  ["0.18 - A LIFE ABOARD", [
    "CREW HAVE LIVES: SHORE LEAVE (THEY KEEP THEIR BERTH), LISTS FOR THE GALLEY, LETTERS CARRIED HOME.",
    "PEOPLE GET SICK. MED SUPPLIES CURE IT AT THE NEXT DOCK; A MEDIC HALVES THE LAY-UP.",
    "AFTER THIRTY DOCKINGS SOMEONE MAY WANT TO GO HOME. HOW YOU PART MATTERS TO THE REST.",
    "THE SHIP WEARS WITH HOURS AND JUMPS. YARD SERVICE AT ANY SHIPYARD; THE BERTH LOG REMEMBERS.",
  ]],
  ["0.17 - A LIVING GALAXY", [
    "A RESCUER CAREER LADDER BUILT FROM LIVES SAVED, REPAIRS, TOWS AND CRISES BROKEN.",
    "COMETS SEED RICH BELTS, SOLAR FLARES COOK HULLS, FESTIVAL WEEKS PAY TOURISTS DOUBLE, DOCK STRIKES DOUBLE YARD PRICES.",
    "BAR RUMOURS POINT AT REAL TROUBLE. A CAPTAIN'S LOG (L ON RECORD) AND A CODEX (C ON SURVEY).",
    "THE COMMS BAND IS ALIVE: CONTROL, HAULERS, PATROLS. SHIPS ARRIVE AND LEAVE THROUGH THE GATES AND DOCK FOR REAL.",
    "CORSAIRS TURNING UP WHILE YOU FIX A FREIGHTER IS A RISK OF ROUGH SPACE NOW, NOT A RULE.",
    "STATIONS HAVE PROFILES AND LOCAL BULLETINS. HAULERS LAUNCH FROM BAYS. NAV LIGHTS BLINK. ENGINES GLOW.",
    "VOID DRIFTERS: SOMETHING LIVES NEAR THE GAS GIANTS. HOLD V NEARBY AND LOG IT.",
    "FACTION ENVOYS: AMNESTIES FOR SALE, CHARTERS AT 75 STANDING (+15% CONTRACT PAY), EMBARGOES BELOW -40.",
    "YOUR SHIP REMEMBERS: A WALL OF RECORD BY THE AIRLOCK (E TO READ), PLAQUES FOR DEEDS, SCORCH WHILE THE HULL IS HURT.",
    "WIND SOUNDS LIKE THE WORLD IT'S ON. STATION PA CHIMES, GATE CRACKS, DRIFTER SONG.",
    "THE MISSING CONVOY: A SECOND CAMPAIGN FOR PILOTS A SYNDICATE TRUSTS. THE TRUTH IS WORTH DIFFERENT THINGS TO DIFFERENT PEOPLE.",
    "OUTPOSTS AND CITIES HAVE MOODS. A LINE ON ARRIVAL TELLS YOU WHAT KIND OF DAY IT IS DOWN THERE.",
    "CREW TALK TO EACH OTHER ABOARD, AND YOU CAN HEAR HOW THEY FEEL ABOUT THE SHIP.",
    "OUTPOSTS HAVE NEEDS (+40% AT THE TRADE DESK) AND A FOREMAN AT THE SURVEY OFFICE WITH GROUND JOBS AND A PLANT TO FIX.",
    "SETTLEMENTS LIGHT UP ON THE NIGHT SIDE FROM ORBIT. AT THE MARKET, ENTER SELLS WHAT YOU HOLD AND BUYS ONLY WHEN YOU HOLD NONE. SHIFT TRADES IN BULK.",
  ]],
  ["0.16 - THE SIGNAL", [
    "A CAMPAIGN: SOMETHING UNDER THE STARLIGHT IS COUNTING. SEVEN STAGES ACROSS THE GALAXY, A FIGHT OR A PARLEY AT THE END.",
    "ENCOUNTERS: FOURTEEN CHOICE CARDS IN FLIGHT AND ON THE GROUND. PODS, SMUGGLERS, CUSTOMS, GHOSTS, WILDLIFE, METEORITES.",
    "CHOICES HAVE CONSEQUENCES: CREW, CARGO, STANDING, MATERIALS, DAMAGE, AND DEBTS PAID BACK AT YOUR NEXT DOCK.",
    "CREW ASK FOR THINGS WHEN YOU DOCK; LOYALTY SURVIVES A BAD WEEK. STAKE UP TO THREE HOMESTEAD CLAIMS (H AT THE LANDER).",
    "MAYDAYS: BOARD A DISABLED FREIGHTER AND FIX IT, OR SEND YOUR ENGINEER ACROSS WHILE YOU HOLD OFF THE CORSAIRS.",
    "OR TOW IT INTO DOCK, OR TAKE THE SURVIVORS ABOARD. STATIONS POST ENGINEERING TENDERS AND CALL CRISES THAT PAY 2.5X.",
    "MEDICS MATTER: FREIGHTERS CALL IN CASUALTIES. STANDING ORDERS PAY MORE WITH EVERY SHIPMENT.",
  ]],
  ["0.15 - SYNDICATES AND TRADE ROUTES", [
    "FOUR AI SYNDICATES PER GALAXY (ALWAYS MARKED AI): BASES WITH CONVOYS, RAIDERS IN RIVAL SPACE, RIVALRY IN THE NEWS.",
    "CONTRACTS AT THEIR BASES BUILD STANDING: AFFILIATES BUY LIKE ALLIES, PARTNERS GET +10% ON WANTED GOODS.",
    "EVERY BASE WANTS THREE GOODS A WEEK AT +30%; SALES FEED ITS TREASURY AND YOUR RUNS DRAW ON THE GALAXY MAP.",
    "DIPLOMACY: RELATIONS DRIFT AND ANSWER TO YOUR CONTRACTS. ALLIANCES SHARE PERKS; DEEP FEUDS BECOME WARS YOU CAN JOIN.",
    "A ROUT TAKES THE LOSER'S BASE AS A HOLDING; THEY FALL BACK TO A PARTNER STATION. HOLDINGS TRADE LIKE HOME BASES.",
    "SQUADRONS WITH A BASE CAN DECLARE FOR A SIDE IN A SYNDICATE WAR: SPOILS TO THE TREASURY, OR A GRUDGE.",
    "THE HUM IS OFF BY DEFAULT NOW: H OR SETTINGS TURNS IT ON.",
  ]],
  ["0.14 - SQUADRON BASES", [
    "A SQUADRON CAN POOL CREDITS AND BUY A CIVILIAN STATION: SHARED VAULT, HALF-PRICE SERVICES,",
    "UPGRADES (DEFENSE GRID, FUEL DEPOT, MARKET STAKE, DEEP VAULT). UNDEFENDED BASES DRAW RAIDERS.",
    "TWO NEW HULLS: ALBATROSS EXPLORER AND OX MINING BARGE. LOST WARS CAN CHANGE A SYSTEM'S FLAG.",
    "WEEKLY BASE CONTRACT AND SQUADRON BOUNTY PAY THE TREASURY. /S TALKS ON YOUR SQUADRON CHANNEL ANYWHERE.",
    "THREE SAVE SLOTS FROM THE TITLE SCREEN, EACH WITH ITS OWN CLOUD CODE. O IN SHIPS PAINTS YOUR TRIM.",
    "MAYDAY: A PILOT UNDER 25% HULL HAILS THE SYSTEM AND OTHERS GET A MARKER. ROVER SUSPENSION AND BATTERY BLUEPRINTS.",
  ]],
  ["0.13 - OTHER PILOTS", [
    "PILOTS IN THE SAME SYSTEM SEE EACH OTHER'S SHIPS. T OPENS THE SYSTEM CHANNEL.",
    "/GIVE AND /PAY HAND OVER GOODS AND CREDITS. KILLS NEAR A WINGMATE ARE SHARED.",
    "SQUADRONS: A SHARED TAG THAT RANKS TOGETHER. THE BEST-STANDING SQUADRON BECOMES",
    "A FACTION'S PATRON. THE GALAXY MAP SHOWS WHERE PILOTS ARE. OPT OUT IN SETTINGS.",
  ]],
  ["0.12 - GROUNDSIDE", [
    "L FROM ORBIT DROPS A ROVER ON ANY REGION: BIOMES, STORMS, NIGHT, OUTCROPS, FLORA,",
    "PROBES, WRECKS. OUTPOSTS, CITIES AND RUINS ARE DOORS ON THE GROUND.",
    "GROUND CONTRACTS ON MISSION BOARDS. A CODEX OF SPECIES AND BIOMES.",
  ]],
  ["0.11 - THE QUIET PROFESSIONS", [
    "TWELVE SHIP MODULES, FUEL SCOOPING, CRUISE (J) AND AUTOPILOT (N), EXPLORATION DATA",
    "AND CAREER RANKS, RARE GOODS, MATERIALS AND AN ENGINEER BAY, CORE MINING WITH",
    "SEISMIC CHARGES, FLEET PARKING, PERMIT SPACE, BLACK MARKETS, WEEKLY COMMUNITY GOAL.",
  ]],
  ["0.10 - DEPTH", [
    "ACHIEVEMENTS, DAILY CONTRACT, HARDCORE MODE, FIVE FACTION ARCS, KEY REBINDING,",
    "MOUSE TURRET AIM, TORPEDOES, PIRATE CAPTAINS, A NEW STARSHIP HUM.",
  ]],
];

export class WhatsNewScene implements Scene {
  touchMode = "menu" as const;
  scroll = 0;
  enter(): void { this.scroll = 0; }
  update(g: Game, dt: number): void {
    void dt;
    if (g.input.wasPressed("Escape") || g.input.wasPressed("Enter") || g.input.mousePressed) { g.setScene("title"); return; }
    const total = NOTES.reduce((a, [, lines]) => a + 9 + lines.length * 8 + 6, 0);
    const max = Math.max(0, total - (VH - 44));
    if (g.input.wasPressed("ArrowDown")) this.scroll = Math.min(max, this.scroll + 24);
    if (g.input.wasPressed("ArrowUp")) this.scroll = Math.max(0, this.scroll - 24);
    if (g.input.wheel) this.scroll = Math.max(0, Math.min(max, this.scroll + g.input.wheel * 24));
  }
  draw(g: Game, ctx: CanvasRenderingContext2D): void {
    void g;
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, VH);
    ctx.save(); ctx.beginPath(); ctx.rect(0, 18, VW, VH - 34); ctx.clip();
    let y = 24 - this.scroll;
    for (const [title, lines] of NOTES) {
      if (y > VH) break;
      if (y + 9 + lines.length * 8 > 18) {
        drawText(ctx, title, 12, y, PAL.ui);
        lines.forEach((l, i) => drawText(ctx, l.slice(0, 112), 12, y + 9 + i * 8, PAL.grey));
      }
      y += 9 + lines.length * 8 + 6;
    }
    ctx.restore();
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, 18); ctx.fillRect(0, VH - 16, VW, 16);
    drawText(ctx, "WHAT'S NEW - UP/DOWN OR WHEEL TO SCROLL", 12, 8, PAL.white);
    drawText(ctx, "ESC BACK", VW - textWidth("ESC BACK") - 12, 8, PAL.greyDark);
    drawText(ctx, "FULL ROADMAP: GITHUB.COM/AES256AFRO/FARSPACE", 12, VH - 12, PAL.greyDark);
  }
}
