// What's new: a short changelog for returning pilots, reachable from the title.

import { Game, Scene, VW, VH } from "../game";
import { drawText, textWidth } from "../gfx/font";
import { PAL } from "../gfx/palette";
import { saveSettings } from "../core/settings";

const NOTES: [string, string[]][] = [
  ["0.56 TO 0.167 - THE LONG DAY", [
    "A HUNDRED AND FORTY-FIVE MILESTONES IN ONE SITTING: THE ROSTER, CORRIDOR TALK, THE RING RACE AND REGATTA, THE POST, STAKES,",
    "THE VOTE, THE BORDER, FLEET AT WORK, THE LINER, MAYDAYS AND NOTES ON THE WIRE, CONVOYS, FAMILY, AND THE REST BELOW.",
  ]],
  ["0.167 - TWO HUNDRED", [
    "MILESTONE TWO HUNDRED. THE HANDBOOK HAS A SECTION FOR THE BRIDGE NOW: ALERTS, PARLEY, THE BRIEFING, REVIEWS,",
    "THE READY ROOM, RANK, ENVOYS AND PATIENTS, THE SIM RIG, BOARDING PARTIES, SHORE LEAVE, AND THE CARDS THAT COME",
    "WHEN A SYSTEM DROPS UNDER FORTY. AND THE LOUNGE KNOWS WHO IT CARRIES; WORD GETS ROUND ON THE PROMENADE.",
    "LETTERS: THE ROCK'S COUNCIL WRITES WHEN THE BELT MAKES YOU A FREEMAN (WE DON'T WRITE TO INNERS), AND THE",
    "INSPECTORATE WRITES AFTER A GOOD SHIP, WITH TWO SPARES ON THE SERVICE'S ACCOUNT. NAVAL STATIONS CONVENE A BOARD OF",
    "INQUIRY FOR EVERY CREW MEMBER WHO DIDN'T MAKE THE POD: TELL IT STRAIGHT, LET NUMBER ONE SPEAK, BLAME THE HULL, OR",
    "DECLINE. AND ONCE A WEEK THE GALLEY TABLE IS A CARD TABLE: DEAL IN FOR FIFTY, PLAY FOR MATCHES, OR WATCH WHO BLUFFS.",
    "THE PLAQUE BY THE AIRLOCK GETS A MOTTO AT THE WALL OF RECORD, YOURS OR THE YARD'S. SOMEBODY REPROGRAMS THE SHIP'S",
    "VOICE AND IT IS, FOR A LEG, INSUFFERABLE. A FREIGHTER WITH A FEVER THAT'S REALLY A QUARANTINE; A SHIP LIKE YOURS OUT",
    "OF A FOLD WITH A LINE FROM A DAY YOU HAVEN'T HAD; AN ENVOY'S COMPANION LOOSE IN THE VENTS (THE CAT CAN HANDLE IT).",
    "NUMBER ONE REPORTS AT THE BRIEFING: WHO'S QUIET, WHETHER THAT WAS ENOUGH RED ALERTS. ON THE GROUND, A SIGNAL FIRE",
    "FROM ANOTHER FACTION'S SURVEY TEAM AND A GARDEN THAT KEPT GOING FOR A CENTURY. AND YOU CAN DICTATE A PERSONAL LOG",
    "ENTRY AT THE WALL OF RECORD, IN YOUR OWN WORDS, WITH THE STARDATE ON IT.",
    "BIRTHDAYS ABOARD: RATION SUGAR AND A CANDLE EVERY THIRTY SHIP-DAYS. SALVAGE RIGHTS: ANOTHER CUTTER ON THE DERELICT,",
    "HALF EACH BY BELT RULES OR ARGUE ABOUT IT. AND EMERGENCIES ON THE BOARDS: A STATION NEXT DOOR NEEDS YOUR ENGINEER AT",
    "THE CLAMP INSIDE THREE HOURS, FULL PAY ON TIME AND HALF AFTER, THE MINUTES ON THE HUD.",
    "THE OFFICE OF ANOMALOUS INCIDENTS WRITES AFTER EVERY FOLD, ECHO AND LOOP, WITH A FORM. WATER SOLD TO A BELT ROCK IS",
    "STANDING. AND NAVAL STATIONS POST PRISONER TRANSFERS: IN IRONS IN THE BUNK ROOM, A GUNNER KEEPS IT SIMPLE, NO GUNNER",
    "AND THEY MAY WALK; ON THE WAY THEY ASK FOR THE CAPTAIN, AND THERE'S A ROCK TWO JUMPS OUT WHERE NOBODY WOULD ASK.",
    "ANSWER THE LAST HAIL FROM THE PAUSE MENU: A CIVIL WORD, BELT MANNERS, OR CLEAR THE BAND. MARINES ON EVERY NAVAL",
    "PROMENADE. AND THE HANDBOOK HAS A PAGE FOR THE SERVICE AND THE BELT.",
    "THE CAPTAIN'S TABLE: TALK TO A FARE AT MESS CALL AND THERE'S A CHAIR AT YOUR END. THE OFFICE SENDS A REPRESENTATIVE",
    "AFTER THE THIRD LETTER, WITH FOUR QUESTIONS. AND AT NAVAL STATIONS AN UNHAPPY OLD HAND MAY ASK FOR A POSTING ASHORE:",
    "SIGN IT WITHOUT A SPEECH, TALK THEM ROUND, OR REFUSE.",
    "OBSERVATION POSTS: THE SURVEY WANTS A QUIET ORBIT OVER A WORLD THAT DOESN'T KNOW ABOUT SHIPS. NO CRUISE, NO RED",
    "ALERT. ROCK KIDS ON EVERY BELT PROMENADE. AND THE SHIP HAS NOTICED THE PLAQUE, THE IRONS, THE OFFICE AND THE ROCKS.",
    "COMMEND YOUR LONGEST-SERVING HAND BEFORE THE ROOM AT A RECEPTION. A DROUGHT ON A BELT ROCK: THE ICE LINE FAILS,",
    "WATER PAYS AND COUNTS TRIPLE. AND STATIONS IN A BAD WEEK POST EVACUATIONS: A PARTY OF UP TO EIGHT AT A HEAD RATE,",
    "LIVES COUNTED AT THE FAR CLAMP.",
    "ANY OTHER BUSINESS AT THE BRIEFING: THE STAFF BRING A MOTION. THE SHIP, ONCE ON THE ROSTER, ASKS FOR ONE QUIET LEG",
    "AND PAYS YOU BACK IN WEAR. AND THE QUIET ONES SET UP SHOP ON THE FLATS: A CRATE IN THE RING FOR A TRADING STONE.",
    "NUMBER ONE WRITES A NOTE IN THE CHRONICLE ABOUT THE CAPTAIN. THE BELT COUNCIL ASKS ITS FREEMEN ABOUT THE WATER",
    "TARIFF. AND A POD TUMBLES PAST WITH AN OFFICER FROM THE FAR SIDE OF A BORDER IN IT, AN HOUR OF AIR LEFT.",
    "ONE ACROSS THEIR BOW AT A PARLEY. THE SHIP KEEPS A NEWSLETTER ON THE GALLEY DOOR (CORRECTIONS: NONE). AND FREEMEN",
    "SEE ROCK-TO-ROCK RUNS AT A FREEMAN'S RATE.",
    "THE NEW HAND GETS SENT FOR A LEFT-HANDED SPANNER. BELT WORDS IN THE HANDBOOK. AND THE PROMENADE HAS STARTED",
    "TALKING ABOUT YOU: THE PLAQUE, NUMBER ONE, THE BOARD, THE WARNING SHOT, WHO SAT AT THE TOP OF THE TABLE.",
    "A MAYDAY FROM THE CORONA. A STOWAWAY BEHIND THE WATER TANK WHO'D LIKE TO BE A CADET. AND THE WORD YOU GIVE WHEN THE",
    "CLAMP LETS GO, CHOSEN AT THE WALL OF RECORD; THE HELM ANSWERS IT.",
    "A WAKE IN THE GALLEY WHEN A NAME COMES OFF THE ROSTER. TALENT NIGHT WITH THREE FIT CREW AND A TORCH FOR A SPOTLIGHT.",
    "AND THE SURVEY'S BOARD OF ETHICS WRITES AFTER A FIRST CONTACT, KEPT OR BROKEN. THE BOARD IS NOT PERMITTED TO THANK YOU.",
    "THE FINDER NAMES THE FIND: NAME THE FIND IN THE PAUSE MENU AFTER A SCAN. THE CREW TALK ABOUT YOUR UNDOCK WORD AND",
    "THE PLAQUE. AND AFTER A ROUGH LEG THE COUNSELLOR KNOCKS WITH TWO CUPS AND WOULD LIKE AN HOUR.",
    "EVERY HULL YOU TAKE AT A YARD IS COMMISSIONED, WITH A STARDATE ON THE PLAQUE AND A BELL. THE SHIP GETS EVEN FOR THE",
    "VOICE SETTINGS. AND THE OFFICE AND THE BOARD OF ETHICS HAVE CODEX ENTRIES UNDER CONTACTS.",
    "THE ROCK'S OTHER COUNCIL ASKS A FREEMAN TO LOOK THE OTHER WAY. THE SHIP MARKS A HUNDRED HOURS SINCE THE BELL. AND A",
    "FIRST ASTRONAUT'S CAPSULE IS COMING DOWN OVER A WORLD THAT HAS NEVER MET A SHIP: GRAPPLE IT, NUDGE IT UNSEEN, OR WATCH.",
    "A RIBBON, PINNED ON CROOKED, WHEN A SPEECH LANDS. NUMBER ONE'S WORD AT YOUR SHOULDER AT A PARLEY. AND THE SHIP",
    "GETS A PARAGRAPH OF ITS OWN IN THE CHRONICLE, IN ITS OWN WORDS.",
    "THE ENGINEER HAS NAMES FOR THE SYSTEMS, AND NOW SO DOES THE HUD: BIG RED (REACTOR CORE) 40%. AN OLD CAPTAIN'S LOG",
    "IN A BOTTLE, STILL READING TO NOBODY. AND THE HANDBOOK HAS CAUGHT UP.",
    "TALK TO A ROCK KID AND THEIR MAM WRITES WITH A DRAWING OF THE SHIP (THERE'S A DOG IN IT). NUMBER ONE IS FIRST IN",
    "LINE FOR THE SHIP WHEN YOU RETIRE. AND THE GALLEY DOOR HAS A SECOND EDITION.",
    "THE LONG SHIP OFF A ROCK TAKES DONATIONS AND PUTS YOUR NAME ON A PLATE NOBODY READS FOR TWO CENTURIES. THE ENVOY",
    "WRITES AFTER THE SIGNING, WITH THE PEN. AND THE CREW LEAVE A NOTE ON THE CONSOLE: A PORT, UNDERLINED TWICE.",
    "SOME DERELICTS KEEP THEIR RECORDER: E ON THE BLINKING BOX FOR THE LAST ENTRY. THE RULE IS TALLIED IN THE HARBOUR",
    "VIEW, KEPT AGAINST BROKEN. AND THE HELP SCREEN KNOWS ABOUT CARD NIGHT, TALENT NIGHT AND THE PAUSE MENU.",
    "TWO CREW WHO ARE CLOSE ASK FOR THE SAME LEAVE. THE CADET CAN COME THROUGH A DERELICT'S LOCK, ON A THIRD OF YOUR AIR.",
    "AND ARRIVING IN A WAR ZONE, TACTICAL GOES TO YELLOW AND SAYS SO.",
    "FLEET REVIEW WEEK AT NAVAL STATIONS: TAKE STATION AT THE END OF THE LINE. HAILS THAT KNOW ABOUT THE DROUGHT, THE",
    "REVIEW AND THE FREEMAN. AND A PHOTOGRAPHER'S SKIFF AT THE GATE: EVERYBODY SAYS NO. EVERYBODY REGRETS IT.",
    "SICKBAY WRITES A NOTE IN THE CHRONICLE. SING ALONG WITH THE BAND, BADLY, AT THE COMMS PANEL. AND HAND THE SHIP",
    "TO NUMBER ONE WHEN YOU GO: THEY HAD THE CONN FOR HALF OF IT ANYWAY.",
    "TALENT NIGHT DOES THE CAPTAIN'S UNDOCK WORD IN SIX MOODS. THE DOCK-HAND HAS NOTICED THE PLAQUE, THE DRAWING AND",
    "WHAT THE REACTOR IS CALLED. AND AT A HUNDRED LIVES ON THE COUNT, THE MEDIC TURNS THE SLATE ROUND.",
    "BOARD A WRECK OF YOUR OWN WHERE SOMEBODY WAS LOST AND SAY THE NAME. GIVE NUMBER ONE THE SHIP FOR A LEG FROM THE",
    "PAUSE MENU (ACTING CAPTAIN ON THE HUD). AND THE HANDBOOK HAS A PAGE FOR THE CREW.",
    "THE STARDATE ON THE INTERIOR HEADER. THE SHIP READS A LINE FROM THE GALLEY DOOR ON UNDOCK, SOMETIMES. AND THE LONG",
    "SHIP AND THE ROCK'S COUNCIL ARE IN THE CODEX.",
    "THE CREW FILL IN THE OFFICE'S FORM, WITH A DIAGRAM. LETTERS TO THE EDITOR ON THE GALLEY DOOR. AND THE ROCK'S",
    "COUNCIL SENDS THE MINUTES AFTER THE VOTE; DON'T READ PAGE FOUR.",
    "CONTROL CLEARS YOU BY RANK AND BAY, AND WELCOMES REGULARS BACK. A TOAST TO THE CHURN AT CARD NIGHT. AND THE",
    "MEDIC'S WORD ON THE HUD WHEN MORALE IS LOW.",
  ]],
  ["0.159 TO 0.166 - DAMAGE CONTROL, THE BELT, SCIENCE, REQUISITION, STATIONS, ORDERS", [
    "AT RED ALERT AN ENGINEER WORKS THE WORST SYSTEM BACK UP WHILE THE GUNS ARE BUSY, AND SAYS SO AT EVERY QUARTER.",
    "A CARD: A SHIP LIKE YOURS, SAME SCORCH, SAME REGISTRY, YOUR OWN VOICE A LITTLE TIRED, SAYING DON'T.",
    "AND THE POOL: THE CREW'S JAR ON THE CONSOLE, WITH A LIST HEADED WHAT THE SKIPPER DOES NEXT.",
    "A STANDING WITH THE ROCKS: HOPPERS HELPED, SPINS RESTARTED, REGISTERS SIGNED AND RUNS DELIVERED COUNT. AT THREE",
    "THE BELT CALLS YOU A FREEMAN AND EVERY ROCK'S YARD IS FIFTEEN UNDER. A SCIENCE OFFICER LABELS THE STRANGE SIGNALS.",
    "RESEARCH STATIONS POST SCIENCE POSTINGS FOR THE FOLDS, LENSES AND ECHOES NEARBY, AT 700CR. AND A CAPTAIN'S CHAIR",
    "FOR THE BRIDGE (500CR): BOLTED DOWN, MORALE +1 MORE EVERY DOCK, THE CREW STAND A LITTLE STRAIGHTER.",
    "REQUISITION: AT COMMANDER AND UP, A NAVAL STATION'S YARD SIGNS FOR A FULL SERVICE ONCE A WEEK. COURTESY OF THE",
    "SERVICE. DON'T MAKE A HABIT OF IT. AND NUMBER ONE'S CONN GOES IN THE SUPPLEMENTAL LOG.",
    "COMPANY: AT MESS CALL YOU SIT WITH WHOEVER'S NEAREST, ONCE A WEEK EACH, AND THEY TALK ABOUT HOME. LOYALTY UP.",
    "A SIXTH SIM PROGRAM, THE PICTURES: AN OLD FILM, THE WHOLE CREW, THE SAME JOKES AT THE SAME LINES, CLOSER FOR IT.",
    "SMALL CEREMONIES: A PROMOTION LIFTS THE WHOLE CREW (THEY STAND THEM A DRINK); NUMBER ONE LAYS IN THE COURSE",
    "WHEN THE AUTOPILOT ENGAGES; A COUNSELLOR ABOARD EASES EVERY FARE A LITTLE AT EVERY DOCKING.",
    "THE REACTOR IS SCRAMMING: A CARD WHEN THE CORE IS UNDER HALF. THE ENGINEER RESTARTS IT BY HAND (NO EYEBROWS),",
    "VENT AND COLD-START ON TEN FUEL, OR RIDE IT OUT. AND NUMBER ONE ASKS WHY YOU'RE AT RED WITH A CLEAR SCANNER.",
    "THE SCRUBBERS ARE FAILING: WHEN THE AIR STARTS TASTING OF THE LAST MEAL, SWAP THE FILTERS WITH A SPARE PART,",
    "BREATHE SHALLOW TO THE NEXT PORT, OR OPEN THE GREENHOUSE TO THE DECK. THE CAT IS FINE. THE CAT IS ALWAYS FINE.",
    "THE HOLD IS DEPRESSURISING (SEAL THE SEAM, SUIT UP, OR DUMP THE BAY) AND THE DRIVE IS COUGHING (RETUNE THE",
    "INJECTORS BY EAR, BURN IT CLEAN, OR NURSE IT TO PORT). THE ENGINEER, IF YOU HAVE ONE, HAS ALREADY GONE QUIET.",
    "COMMS DOWN (THE ENGINEER UP THE MAST, THE SIM RIG'S EMITTER WITH A FAINT PIANO, OR FLY QUIET AND TALK TO EACH",
    "OTHER) AND THE MOUNTS JAMMED (THE GUNNER WITH A PRY BAR, A HARD CYCLE, OR THE TURRET LOCKED FORWARD LIKE A DARE).",
    "THE HUD'S TOP-LEFT WARNINGS FLAG ANY SYSTEM UNDER FORTY, SO THE CARDS DON'T COME AS A SURPRISE, AND THE HARBOUR",
    "VIEW SAYS WHAT THE YARD WOULD LIKE A WORD ABOUT.",
    "AN ENVOY BOUND FOR A SYSTEM AT WAR IS AN ENVOY THROUGH THE LINES: THE FARE IS HALF AGAIN AND THE REP IS BETTER.",
    "AND A SHIP ON ITS OWN ROSTER REVIEWS THE CAPTAIN AT THE WALL OF RECORD. YOU RUN ME HARD. I'D LIKE THAT NOTED.",
    "STATIONS: THE HUD NAMES WHO HAS THE CONN ON AUTOPILOT, WHO'S AT TACTICAL AND ON DAMAGE CONTROL AT RED.",
    "AND THE HELM SAYS STEADY AS SHE GOES WHEN YOU DROP OUT OF CRUISE.",
    "STANDING ORDERS IN SETTINGS: LEAVE THE CLAMP AT GREEN OR AT YELLOW WITH THE SHIELDS READY, AND WHETHER NUMBER ONE",
    "ANSWERS THE PASSING HAILS WHILE THE AUTOPILOT HAS THE CONN.",
    "THE LOUNGE KNOWS WHO IT CARRIES: ENVOYS AND PATIENTS HAVE THEIR OWN QUESTIONS FOR THE PILOT, THE ENGINEER, THE",
    "MEDIC AND THE GUNNER. IF WE'RE FIRED ON, DO NOT FIRE BACK. THAT'S NOT A REQUEST. IT'S A TREATY.",
    "WORD GETS ROUND: THE BULLETIN CARRIES THE REGISTER AND THE FREEMEN, THE TANNOY SHOWS A SHIP THAT PASSED",
    "INSPECTION TO THE APPRENTICES, AND THE CONCOURSE KNOWS A FREEMAN OF THE BELT WHEN IT SEES ONE.",
  ]],
  ["0.158 - KEEPING II", [
    "THE CHRONICLE CARRIES THE LOG'S LAST FIVE ENTRIES. THE CODEX COUNTS ENVOYS LANDED AND PATIENTS SAVED. AND AT",
    "COMMODORE AND UP, NOW AND THEN, SOMEBODY WITH MORE BRAID THAN YOU WALKS YOUR DECK: WEAR, MORALE, THE DECK, THE",
    "HULL, FOUR MARKS. A GOOD SHIP, COMMODORE. OR: WE'LL BE IN TOUCH.",
    "AND THE POOL: A JAR ON THE CONSOLE WITH A LIST TAPED TO IT, HEADED 'WHAT THE SKIPPER DOES NEXT'. TAKE THE JAR,",
    "LET IT RIDE, OR DOUBLE IT AND PICK A LINE. YOU ARE WRONG ABOUT YOURSELF, WHICH THE CREW FIND REASSURING.",
  ]],
  ["0.157 - SECOND ACTS", [
    "EVERY FACTION'S STORY ARC HAS A SECOND ACT: TWO MORE STAGES AFTER THE THIRD, AT SEVENTY-FIVE AND A HUNDRED REP.",
    "THE COMPACT'S FIRST CONTACT PROTOCOL, THE GUILD'S DRY ROCK AND THE REGISTER'S PRICE, THE COMBINE'S LEDGER, THE",
    "AUTONOMY'S OUTER SIGNAL, THE VEIL'S INTEREST IN THE HULL THAT SANG. THE RECORD COUNTS TO TWENTY-FIVE NOW.",
    "WHERE A STATION'S CRISIS IS MEDICINE, THE CLAMP ASKS: SEND THE MEDIC DOWN FOR A SHIFT, HAND OVER CRATES, OR KEEP",
    "THE MASK ON. AND THE READY ROOM ON THE PAUSE MENU: A WORD WITH NUMBER ONE, ONCE A LEG. THEY SAY WHAT THEY SEE.",
  ]],
  ["0.156 - A LINE ON THE ROSTER", [
    "ONCE IT HAS A NAME, THE SHIP ASKS TO BE ON THE ROSTER. IT DOESN'T NEED A WAGE. IT WOULD LIKE A LINE. SAY YES",
    "AND IT GETS ONE AT THE BOTTOM, WITH ITS OWN MOOD (FINE, HUNGRY, HOLED, ACHING). THE CREW ADDRESS THE CEILING.",
    "AND THE QUIET ONES: A SECOND CONTACT ON THE GROUND, IN LIGHTS, THREE, FIVE, THREE.",
    "A NEW GALAXY EVENT: A BELT ROCK DECLARES ITSELF INDEPENDENT FOR THE WEEK. WATER, RATIONS AND MEDICINE PAY, THE",
    "TANNOY HAS OPINIONS, AND A REGISTER BY THE CLAMP ASKS WHO'S WITH THE ROCK. SIGN, TRADE QUIETLY, OR REPORT IT.",
  ]],
  ["0.155 - SHORE LEAVE", [
    "L AT THE LANDER WITH CREW ABOARD: AN HOUR ON THE GROUND UNDER A SKY THAT ISN'T A CEILING (MORALE, AND MAYBE",
    "A FIND THE SURVEY MISSED), A PHOTO BY THE LANDER WITH EVERYONE IN IT FOR THE KEEPSAKES, OR BACK TO WORK.",
    "THE QUIET ONES, ON THE GROUND: LIGHTS ON A RIDGE THAT ANSWER THE ROVER'S HEADLIGHTS, THREE, FIVE, THREE. ANSWER",
    "THEM, AND LATER A LINE OF LIGHTS LEADS YOU SOMEWHERE PATIENT. A SECOND CONTACT FOR THE CODEX, AND A STONE.",
  ]],
  ["0.154 - ALL HANDS", [
    "ADDRESS THE CREW FROM THE PAUSE MENU, ONCE A LEG: RALLY THEM (MORALE, AND THE NEXT ALERT SITS EASIER), WARN",
    "THEM (YELLOW ALERT, NOBODY SURPRISED), OR THANK THEM BY NAME (LOYALTY). AND THE ENGINEER GIVES A DAMAGE REPORT",
    "THE FIRST TIME THE HULL DROPS UNDER HALF: I CAN HOLD HER TOGETHER IF YOU STOP GETTING HER HIT.",
    "BOARDING A DERELICT ASKS WHO COMES THROUGH THE LOCK WITH YOU: THE ENGINEER (BREACHES DRAIN HALF AS FAST, FIRES",
    "SPREAD SLOWER), THE MEDIC (A SPARE TANK, A THIRD MORE AIR), THE GUNNER (THE FIRES BY THE LOCK ARE OUT), OR ALONE.",
  ]],
  ["0.153 - SCIENCE OFFICER", [
    "A THIRD SPECIALTY FOR PILOTS: SCIENCE OFFICER. THE DEEP SCAN REACHES HALF AGAIN AS FAR AND STRANGE READINGS",
    "PAY HALF AGAIN. THE SHIP HAS A LINE AT THE BRIEFING NOW (I'M FINE. ASK ME AGAIN AFTER THE JUMP). AND A CARD:",
    "A HOSTAGE ON THE BAND. PAY THE RANSOM, TALK THEM DOWN, OR GO AND GET THEM. THEY'D LIKE THAT TOO.",
    "ON THE NIGHT SHIFT A BAND PLAYS THE PROMENADE. E TO STAND FOR A SET, ONCE A WEEK PER STATION: THE CREW DRIFT",
    "OVER, THE FARES TOO, SOMEBODY REQUESTS THE ONE ABOUT THE GATE. ONE MORE, THEN THE BAR CLOSES. IT DOESN'T.",
  ]],
  ["0.152 - PARLEY", [
    "E NEAR A CORSAIR OPENS A CHANNEL INSTEAD OF THE GUNS: PAY THE TOLL (120CR A HULL), BLUFF A PATROL CALLSIGN IN A",
    "PATROL VOICE (A GUNNER, A RANK AND A REPUTATION HELP), OFFER THEM A WAY OUT IF YOU'RE AN ACE THEY'VE HEARD OF,",
    "OR OPEN FIRE. TALK ONE DOWN WITHOUT A SHOT AND IT'S A DEED.",
    "SMALL VOICES: WITH A COUNSELLOR ABOARD, E BESIDE A LOW CREW MEMBER SENDS THEM INTO THE STUDY FOR TWENTY MINUTES",
    "(ONCE A LEG). THE HELM CALLS THE FLIP AND BURN WHEN YOU BRAKE HARD AT SPEED. ALONE ABOARD, THE CAT HAS THE CONN.",
  ]],
  ["0.151 - PATROL ORDERS", [
    "ONCE YOU HOLD A RANK (LIEUTENANT, TEN DEEDS), MILITARY STATIONS POST PATROL ORDERS: HOLD STATION IN A SYSTEM",
    "FOR A MINUTE AND A HALF OR MORE, OFF CRUISE, SHOW THE FLAG, AND REPORT BACK. THE HUD COUNTS THE SECONDS.",
    "BELT WORK: BOARDS NEAR THE ROCKS POST WATER, RATION, CLINIC AND FILTER RUNS IN THE ROCK'S OWN WORDS. AND NOW AND",
    "THEN A ROCK LOSES ITS SPIN AS YOU CLAMP ON: SEND THE ENGINEER UP THE SPOKE, WAIT IT OUT, OR LEAVE THEM TO IT.",
  ]],
  ["0.150 - A VISITOR ON THE BRIDGE", [
    "SOMEBODY IN THE OTHER CHAIR WHO WAS NOT IN THE OTHER CHAIR, DRESSED FOR A BETTER PARTY, WITH A SMALL GAME.",
    "PLAY IT AND TAKE YOUR CHANCES; REFUSE POLITELY AND IMPRESS THEM; OR TELL THEM IT'S YOUR SHIP. THE CHAIR STAYS",
    "WARM AN HOUR. AND THE SHIP READS THE OLD LOG BACK ON THE NIGHT WATCH. IT KEEPS THESE. SOMEBODY SHOULD.",
    "STRANGE READINGS AMONG THE SIGNALS IN NEW GALAXIES: A FOLD THAT SKIPS THE CLOCK FIFTEEN MINUTES NOBODY REMEMBERS,",
    "A LENS THAT LIGHTS EVERY SIGNAL IN THE SYSTEM, AN ECHO THAT PLAYS THE SHIP'S OWN BAND BACK. THE CODEX KEEPS THEM.",
  ]],
  ["0.148 AND 0.149 - RANK, REGISTRY, A WORD, THE VILLAGE", [
    "YOUR DEEDS ON THE WALL ADD UP TO A RANK ON THE LANES: SKIPPER, LIEUTENANT AT TEN, COMMANDER AT TWENTY-FIVE,",
    "CAPTAIN AT FORTY-FIVE, COMMODORE AT SEVENTY, ADMIRAL AT A HUNDRED. THE HULL HAS A REGISTRY, FS AND FOUR DIGITS.",
    "CONTROL READS BOTH OUT ON THE WAY IN. THE HAULERS GET NERVOUS AROUND A COMMODORE.",
    "RUN THE CREW LOW ENOUGH (TOO MANY ALERTS, TOO MANY BURNS, TOO LONG BETWEEN PORTS) AND THEY MEET YOU AT THE CLAMP:",
    "A BONUS ROUND, A NIGHT ASHORE ON YOU, OR YOUR FOOT DOWN. HALF THE TIME THEY RESPECT IT. HALF THE TIME SOMEBODY WALKS.",
    "THE VILLAGE, ON THE GROUND: SMOKE FROM COOKFIRES WHERE THE SURVEY SAID GEOLOGY. BACK OUT QUIETLY (THE RULE),",
    "GO DOWN WITH YOUR HANDS OPEN, OR HELP WITH THE FIRE. THE RULE WAS WRITTEN BY SOMEBODY WHO WASN'T THERE.",
  ]],
  ["0.147 - BRIDGE PROTOCOL", [
    "A THIRD SPECIALTY FOR MEDICS: SHIP'S COUNSELLOR. RED ALERT WEARS THE CREW HALF AS FAST AND REVIEWS LAND BETTER.",
    "WITH THE AUTOPILOT FLYING AND A NUMBER ONE ABOARD, THEY ACKNOWLEDGE THE PASSING HAILS: THE CAPTAIN'S BELOW.",
    "AND THE HELM ANSWERS WHEN CRUISE ENGAGES. AYE, CAPTAIN. DON'T SAY IT. FINE, SAY IT.",
  ]],
  ["0.146 - SUPPLEMENTAL", [
    "AT EVERY CLAMP THE CAPTAIN'S LOG GETS A SUPPLEMENTAL ENTRY IN THE CAPTAIN'S VOICE: THE HOURS SINCE THE LAST",
    "DOCK, THE JUMPS, FIRE TAKEN, RED ALERTS, A HARD BURN, THE THINGS ON THE LANE WORTH WRITING DOWN, THE RESCUES,",
    "AND HOW THE CREW ARE HOLDING UP. THE CHRONICLE READS BETTER FOR IT.",
    "THE ENVOY'S RITE: A CARD WHILE A TREATY FARE IS ABOARD. THE GALLEY FOR AN HOUR, JOIN THEM (ONE WORD, THEN TEA),",
    "OR TELL THEM THE GALLEY IS THE GALLEY. NEW CREW TRAITS FROM THE BELT AND THE INNERS, WITH THE LINES TO MATCH.",
  ]],
  ["0.144 - THE UNWINNABLE, AND THE TRAP", [
    "A FIFTH SIM PROGRAM: THE UNWINNABLE. A FREIGHTER ON THE WRONG SIDE OF A LINE, AND EVERYTHING THAT COMES FOR YOU.",
    "YOU LOSE. UNLESS THE ENGINEER CHANGES THE CONDITIONS. AND A CARD: A DISTRESS CALL THAT IS A LITTLE TOO STRONG.",
    "ANSWER IT, SCAN IT FIRST WITH A GUNNER OR A DISCOVERY SCANNER, OR FLY ON. IT IS REAL ABOUT HALF THE TIME.",
    "A TRANSLATOR CORE AT THE SHIPYARD (900CR): FIRST CONTACTS ALWAYS LAND AND THE SINGERS SAY A THIRD THING.",
    "TACTICAL GOES TO YELLOW ON ITS OWN WHEN A HOSTILE CLOSES, IF NOBODY HAS. RED IS STILL YOUR CALL.",
    "DIPLOMATIC PASSAGE: WITH AN ENVOY ABOARD, CUSTOMS READS THE SEAL AND BACKS OFF. NOBODY OPENS A TREATY SHIP.",
    "THE KLAXON KEEPS GOING WHILE YOU HOLD RED. YOU'LL WANT TO STAND DOWN EVENTUALLY.",
  ]],
  ["0.143 - REVIEWS", [
    "V ON THE ROSTER: A REVIEW IN THE STUDY, THE DOOR SHUT, THE KETTLE ON, ONCE A WEEK PER CREW MEMBER. COMMEND",
    "THEM (MORALE AND LOYALTY), COUNSEL THEM (A STEP TOWARD THE NEXT SKILL), OR MAKE THEM NUMBER ONE. THEY KNOW",
    "WHAT THIS IS. THE REST OF THE CREW FIND OUT WITHIN THE MINUTE.",
    "TWO MORE CARDS: THE LOUNGE AT WAR (SEAT THEM APART, A CAPTAIN'S DINNER, OR LET THEM HAVE IT OUT) AND AN INNER",
    "AND A BELTER IN YOUR OWN CREW, ARGUING ABOUT THE WATER RATION UNTIL YOU SIT THEM DOWN.",
    "AN AWAY TEAM ON THE GROUND: A DOOR IN THE ROCK AND A LIGHT THAT SHOULDN'T BE ON. SEND THE ENGINEER, THE MEDIC,",
    "THE GUNNER, OR GO YOURSELF. EVERYBODY SAYS NOT TO. THE CREW LIKE A CAPTAIN WHO GOES IN FIRST.",
  ]],
  ["0.142 - SHE HAS A NAME", [
    "THE SHIP HAS HAD A NAME FOR A WHILE. NOBODY ASKED. THE WALL OF RECORD KNOWS HOW: ASK, AND IT SPELLS IT OUT",
    "ON THE BAND, LETTER BY LETTER. FROM THEN ON ITS LINES ARE SIGNED THAT WAY. THE CAT STILL WON'T USE IT.",
    "A FOURTH REQUEST FROM THE LOUNGE: THE STAR UP CLOSE. AND A CARD THAT REPEATS THE SAME MINUTE, COFFEE AND ALL,",
    "UNTIL YOU DO SOMETHING DIFFERENT. THE CREW LEARN TO USE THE MINUTE.",
  ]],
  ["0.141 - ALERT STATUS", [
    "Y IN FLIGHT CYCLES THE ALERT: YELLOW READIES THE SHIELDS (RECHARGE HALF AGAIN AS FAST); RED READIES EVERYTHING",
    "(SHIELDS TWICE AS FAST, GUNS +10%) AND WEARS THE CREW DOWN A POINT EVERY HALF MINUTE. A BANNER, A KLAXON, AND",
    "WHOEVER'S AT TACTICAL CALLING STATIONS. THE CLAMP STANDS YOU DOWN.",
    "PASSING HAILS: THE UNNAMED TRAFFIC TALKS AS IT PASSES. PATROLS ARE FORMAL, HAULERS ARE BELT OR BUSINESS, LINERS",
    "ARE SMUG, AND EVERYBODY HAS A WORD ABOUT THE CAT. GO TO RED ALERT NEAR THEM AND THEY'LL ASK WHY.",
    "RECEPTIONS: DOCK WITH STANDING (REP 20+) AND NOW AND THEN THE FACTION THROWS ONE IN YOUR HONOUR, ONCE A WEEK.",
    "MAKE A SPEECH (SHORT IS GOOD), BRING A GIFT FROM THE HOLD, OR PLEAD A LONG DAY. THEY REMEMBER ALL THREE.",
  ]],
  ["0.140 - THE SINGERS", [
    "A FIRST-CONTACT ARC IN THREE CARDS: ANSWER THE HULL THAT SINGS, GUIDE IT TO THE BRIGHTEST THING IN THE SYSTEM",
    "(A LIT BEACON, A WONDER, OR THE CREW SINGING THE WAY), AND TAKE WHAT IT LEAVES: A SHARD THAT HUMS ON THE SEAT.",
    "THE CODEX HAS A CONTACTS PAGE. THE SHIP HAS A KEY NOW.",
    "BRIDGE BANTER: TWO OF THE WATCH TRADE A LINE ON THE BAND IN FLIGHT NOW AND THEN, WHEN THE CHANNEL IS QUIET.",
    "THE BELT REMEMBERS: MINING AND REFINERY ROCKS HAVE THEIR OWN TANNOY, AND ONCE YOU'VE SHARED AIR OR WATER WITH",
    "A ROCK HOPPER THEIR YARDS ARE TEN UNDER FOR YOU. DON'T TELL THE INNERS.",
  ]],
  ["0.139 - SENIOR STAFF", [
    "E AT THE STUDY WITH TWO CREW ABOARD, ONCE A LEG: ENGINES, SICKBAY, HELM AND TACTICAL REPORT ROUND THE TABLE,",
    "AND THE CAPTAIN SETS A FOCUS UNTIL THE NEXT DOCK: WEAR 20% SLOWER, MORALE AND THE SICK, FASTER SHIELDS, OR",
    "CHEAPER JUMPS. THE HUD SAYS WHICH. 'DISMISSED.'",
    "A SIM RIG FOR THE DECK (700CR AT ANY SHIPYARD): THE BEACH, FRONTIER TOWN, THE OPERA HOUSE, HOME PORT IN SPRING.",
    "AN HOUR SOMEWHERE ELSE ONCE A LEG, MORALE UP, THE FARES INVITED TO THE OPERA. IT JAMS SOMETIMES.",
  ]],
  ["0.138 - THE JUICE", [
    "THE CLINIC ON THE PROMENADE IS A MENU NOW: TREAT THE SICK, OR BUY BURN JUICE AT 150CR A DOSE, THREE AT MOST.",
    "HARD BURN FROM THE PAUSE MENU IN FLIGHT: CRUISE 40% FASTER AND KEENER THRUST UNTIL YOU DOCK OR JUMP.",
    "THE CREW LOSE MORALE AND THE FRAME TAKES WEAR. COURIERS AND ENVOYS ON A DEADLINE WILL FORGIVE YOU.",
    "MEDICAL RUNS: A PATIENT IN THE LOUNGE NEEDS THE CLINIC AT THE NEXT STATION OVER, WITHIN THEIR DOCKINGS.",
    "A MEDIC ABOARD BUYS ONE MORE; MED SUPPLIES HELP THEIR MOOD; LATE HALVES THE FARE. THE HUD SAYS STABLE OR CRITICAL.",
  ]],
  ["0.137 - CAPTAIN'S LOG", [
    "THE CHRONICLE AND THE LOG OPEN WITH A STARDATE. THE LONGEST-SERVING CREW MEMBER IS NUMBER ONE, ON THE ROSTER",
    "AND IN THE CORRIDORS. BRIDGE BANTER, A SHIP WITH A DEADPAN, AND THE BELT TALKING ABOUT INNERS ON THE CONCOURSE.",
    "ENVOY FARES IN THE LOUNGE: A TREATY BETWEEN TWO FACTIONS ON A DEADLINE. LAND IT IN TIME AND UNSHOT FOR REP",
    "ON BOTH SIDES, OR THE TALKS FAIL. THE TREATY'S STATE RIDES ON THE HUD LINE.",
  ]],
  ["0.136 - THE HARBOUR VIEW", [
    "O ON THE RECORD TAB: THE STATION CLOCK AND THE YARD'S RATE, WHO IS IN THE BAYS, LOST PROPERTY AND KEEPSAKES,",
    "OPEN REQUESTS FROM THE LOUNGE, AND EVERYTHING THE TANNOY WOULD PAGE YOU ABOUT, WITHOUT WALKING THE DECK.",
    "A FARE'S OPEN REQUEST RIDES ON THEIR LINE ON THE FLIGHT HUD: WANTED, DONE, OR A QUIET RUN BROKEN.",
    "AWAY TEAMS: TEN NEW CARDS. A HULL THAT SINGS IN NO KNOWN TONGUE, A QUIET WORLD THAT NEEDS MEDICINE IT ISN'T",
    "SUPPOSED TO KNOW ABOUT, A ROCK HOPPER FAMILY OUT OF AIR, A CASE UNDER HARD BURN, TALENT NIGHT, THE SIM RIG",
    "STUCK ON A WESTERN, A DIPLOMAT WITHOUT A SHIP, AN ANOMALY, A PLACE SOMEBODY BUILT, THE OUTPOST'S ONE BAR.",
  ]],
  ["0.135 - HANDBOOK III", [
    "THE HELP SCREEN AND THE HANDBOOK COVER THE HARBOUR NOW: HOURS AND RATES, PAGING, THE DOCK-HAND, BERTH",
    "NEIGHBOURS, LOST PROPERTY, REQUESTS FROM THE LOUNGE, THE GALLEY. THE SHIP HAS A FEW NEW THINGS TO SAY TOO.",
  ]],
  ["0.134 - SOMETHING OF THEIRS", [
    "A NEW CARD ON THE LANES: THE OWNER OF SOMETHING LEFT IN YOUR CABIN CHASES THE SHIP DOWN, OUT OF BREATH.",
    "HAND IT OVER ON A LINE FOR 80CR PRESSED ON YOU, OR KEEP IT AND WATCH THEM TURN FOR HOME.",
  ]],
  ["0.133 - TALK OF THE DECK", [
    "THE CREW NOTICE THE NEW THINGS: A KEEPSAKE ON THE SEAT, LOST PROPERTY WAITING, THE DOCK-HAND'S FREE PATCH, THE",
    "CAPTAIN HUGGING A BERTH NEIGHBOUR, A FARE'S OPEN REQUEST, THE NIGHT RATE. THE CONCOURSE GOSSIPS ABOUT WHO IS IN.",
  ]],
  ["0.132 - THE GALLEY MENU", [
    "THE GALLEY COOKS FROM WHAT IS ABOARD. LUXURIES MAKE IT A PROPER DINNER AND THE FARES' MOOD LIFTS; A RARE TEA,",
    "WINE OR MEAD IS POURED AFTER AND NOT USED UP; THE COOK HELPS. EVERY MEAL FEEDS A FARE WHO ASKED FOR ONE.",
    "THE CHRONICLE COUNTS MEALS COOKED AND WHAT WAS KEPT ABOARD.",
  ]],
  ["0.131 - DEEDS III", [
    "SIX MORE DEEDS ON THE WIRE: ON THE HOUSE, LOST AND FOUND, FINDERS KEEPERS, GOOD SERVICE, BERTH NEIGHBOURS,",
    "AND NIGHT OWL, FOR DOCKING ON A STATION'S NIGHT SHIFT.",
  ]],
  ["0.130 - LOST PROPERTY", [
    "FARES LEAVE THINGS IN THE CABIN: A SCARF, A HARMONICA, A CHESS SET MID-GAME. THE PASSENGER SEAT LISTS THEM.",
    "HAND THEM IN AT A HARBOURMASTER'S OFFICE (50CR WHERE THEY GOT OFF, 20CR FORWARDED) OR KEEP THEM AFTER FOUR",
    "DOCKINGS: KEEPSAKES, ON THE WALL OF RECORD.",
  ]],
  ["0.129 - REQUESTS FROM THE LOUNGE", [
    "A PASSENGER ASKS FOR SOMETHING ON THE LEG, ON COMMS FROM THE LOUNGE: A HOT MEAL, A QUIET RUN, OR A VIEW.",
    "SERVE THE MESS, ARRIVE WITHOUT TAKING FIRE, OR SHOW THEM SOMETHING, AND THEY TIP ON TOP OF THE FARE AT THE END.",
  ]],
  ["0.128 - THE DOCK-HAND", [
    "SOMEONE MEETS YOUR SHIP AT THE CLAMP AND HAS ALREADY LOOKED HER OVER: THE HOLE, THE RATTLE, THE FUMES, THE FULL",
    "HOLD, THE GREEN FARES, THE CAT AT THE AIRLOCK. E BY YOUR BAY FOR THEIR OPINION. REGULARS GET A SMALL JOB ON THE HOUSE",
    "ONCE A WEEK: A PLATE, A SPLASH IN THE TANK, OR GREASE ON WHAT RATTLES.",
  ]],
  ["0.127 - STATION HOURS MATTER", [
    "THE HOUR SETS THE RATE. NIGHT SHIFT: HULL WORK AND SERVICING 15% OVER. EARLY SHIFT, BEFORE ELEVEN: 10% UNDER.",
    "FUEL IS FUEL. THE LOUNGE FILLS AFTER DARK; NIGHT CONTROL ASKS YOU TO KEEP IT QUIET. THE NEXT PORT KEEPS ITS OWN CLOCK.",
    "THE SHIPYARD LIST SCROLLS WITH THE CURSOR NOW, AND LONG NOTES SIT ON THE INFO LINE INSTEAD OF OVER THE ROW.",
  ]],
  ["0.126 - BERTH NEIGHBOURS", [
    "CAPTAINS YOU KNOW WALK THE PROMENADE WHEN THEIR SHIP IS IN THE BAYS: HOME-PORT CAPTAINS YOU HAVE MET,",
    "FRIENDS PASSING THROUGH, THE RIVAL WHENEVER THEY ARE HOME. E FOR A WORD; ONCE A WEEK A FRIEND SETTLES A ROUND",
    "OR HANDS OVER A SPARE. THEIR HULL SITS IN THE FAR BAY AND THE TANNOY SAYS WHO IS IN.",
  ]],
  ["0.125 - PAGING", [
    "THE TANNOY KNOWS WHO IS BERTHED. MAIL WAITING, THE CAT LEFT BEHIND, FAMILY ON THE PROMENADE, A CONSIGNMENT",
    "THE HARBOURMASTER IS EXPECTING, A HULL TRAILING SOMETHING, A TANK ON FUMES: THE STATION SAYS SO, TWICE.",
    "LONG CALLS WRAP ON THE PROMENADE AND SCROLL THROUGH A WINDOW ON THE SERVICES SCREEN. NOTHING IS CUT SHORT.",
  ]],
  ["0.124 - CONVOY MANNERS", [
    "DOCK WITH A CONVOY ON YOUR STERN OR A RACE RUNNING AND THEY LET YOU GO WITH A WORD, NOT A SILENT VANISH.",
  ]],
  ["0.123 - PICTURES IN THE MUSEUM", [
    "A PICTURE JOB TURNED IN AT A RESEARCH STATION HANGS IN ITS MUSEUM WITH YOUR NAME UNDER IT.",
  ]],
  ["0.122 - KEEPSAKES II", [
    "THE CHRONICLE CARRIES THE GUESTBOOK. THE WALL OF RECORD LISTS YOUR RING TIMES. THE ROSTER TOTALS THE WAGES.",
  ]],
  ["0.121 - HANDBOOK INDEX", [
    "THE HANDBOOK'S HEADER LISTS ITS SECTIONS. THE SHIP HAS OPINIONS ABOUT THE VOTE.",
  ]],
  ["0.120 - TIDY II", [
    "THE TITLE SUMMARY CARRIES YOUR NAME ON THE LANES. THE HANDBOOK KNOWS THE PACER, THE WAGER AND CONVOYS ON THE BOARD.",
  ]],
  ["0.119 - CONVOY ON THE BOARD", [
    "STATIONS POST CONVOYS ON THE MISSIONS BOARD. ACCEPT ONE AND IT FORMS ON YOUR STERN WHEN YOU LAUNCH.",
  ]],
  ["0.118 - ODDS AND ENDS II", [
    "THE CHAMPION GETS TALKED ABOUT. FARES BOARD IMPRESSED WHERE YOU HOLD THE RINGS. THE ROSTER MARKS FAMILIES MET.",
  ]],
  ["0.117 - PEOPLE IN THE CODEX", [
    "THE CODEX COUNTS THE PEOPLE: CAPTAINS MET, NOTABLES CARRIED, OLD SHIPMATES, FAMILIES VISITED.",
  ]],
  ["0.116 - THE LANES REPORT", [
    "YOUR HOME PORT'S HARBOUR OFFICE WRITES EACH NEW WEEK: THE BORDER, YOUR HOLDINGS, YOUR BERTH.",
  ]],
  ["0.115 - THE MARSHAL'S CHALLENGE", [
    "A MARSHAL'S TENDER MAY OFFER A WAGER: THE NEXT RUN UNDER PAR PAYS DOUBLE. BIG SHAREHOLDERS GET A BAY OF THEIR OWN.",
  ]],
  ["0.114 - UNREAD", [
    "THE TITLE MARKS WHAT'S NEW WHEN THERE'S SOMETHING YOU HAVEN'T READ.",
  ]],
  ["0.113 - THE GRAND COURSE", [
    "THE REGATTA'S LAST COURSE IS EIGHT WIDE RINGS. THE CONVOY LEAD TALKS ON THE WAY TO THE GATE.",
  ]],
  ["0.112 - CHEQUES IN THE POST", [
    "YOUR OTHER HOLDINGS PAY A QUARTER DIVIDEND WHEREVER YOU DOCK. THE GUESTBOOK IS READABLE AT THE PASSENGER SEAT.",
  ]],
  ["0.111 - THE PACER", [
    "A GHOST RUNS THE RINGS AT THE RECORD PACE SO YOU CAN SEE IF YOU'RE UP OR DOWN. THE FIRST DOCK OF A WEEK ANNOUNCES THE WEEK.",
  ]],
  ["0.110 - TIDY", [
    "THE HANDBOOK COVERS SCRAPPING AND WRITING BACK; THE SHIP HAS A WORD ABOUT FAMILY AND LETTERS.",
  ]],
  ["0.109 - GUIDE CONTENTS", [
    "THE PLAYER'S GUIDE HAS A GROUPED CONTENTS. BORDER RESULTS YOU PUSHED FOR GO TO THE WIRE.",
  ]],
  ["0.108 - LOOSE ENDS", [
    "RECORD HOLDERS WRITE WHEN YOU BEAT THEM. RACE DAY PAYS HALF AGAIN. TOURISTS WANT A COPY OF THE POSTCARD.",
  ]],
  ["0.107 - WRITING BACK", [
    "R ON THE NEWS TAB WRITES BACK TO YOUR LATEST LETTER. CAPTAINS REMEMBER WHO ANSWERS.",
  ]],
  ["0.106 - DEEDS AND SLOTS", [
    "FIVE MORE DEEDS ON THE RECORD, AND THE SAVE SLOTS SHOW YOUR NAME ON THE LANES.",
  ]],
  ["0.105 - THE CHRONICLE'S WEEK", [
    "THE CHRONICLE TELLS THE WEEK: YOUR VOTES, THE BORDER, YOUR HOLDINGS AND TIMES, AS PROSE.",
  ]],
  ["0.104 - SMALL TOUCHES", [
    "SPECIALTIES IN THE CHRONICLE, THE BORDER ON THE BAND, A HARDCORE LOSS LEAVES A WRECK ON THE CHART, YOUR NAME ON POSTCARDS.",
  ]],
  ["0.103 - CALLS AND COURSES", [
    "THE GALAXY MAP LISTS THIS WEEK'S CALLS FOR HELP. N ON THE MARKET PLOTS A COURSE TO THE BEST KNOWN SELL.",
  ]],
  ["0.102 - HUM", [
    "THE TANNOY SPEAKS WHILE YOU TRADE. THE SHIP CALLS THE WATCH CHANGE. THE LOUNGE IS ON THE BAND.",
  ]],
  ["0.101 - SCRAP", [
    "X ON A PARKED HULL SELLS HER TO THE YARD FOR SCRAP. CREDITS TODAY; NO GETTING HER BACK.",
    "THE TITLE TICKER SHOWS THIS WEEK'S CONTESTED SYSTEM AND HOW IT STANDS.",
  ]],
  ["0.100 - FAMILY", [
    "DOCK AT A CREW MEMBER'S HOME PORT AND SOMEONE OF THEIRS IS ON THE PROMENADE. TALK TO THEM.",
  ]],
  ["0.99 - GENTLE LANES", [
    "SETTINGS HAS THE LANES: GENTLE, NORMAL OR ROUGH. HALF THE CORSAIRS IF YOU'D RATHER TRADE, TALK AND RACE.",
  ]],
  ["0.98 - PORTS REMEMBER YOU", [
    "THE HARBOURMASTER'S OFFICE HAS YOU ON FILE: DOCKINGS, YOUR STAKE, FARES LANDED, YOUR VOTE, YOUR RING TIMES.",
  ]],
  ["0.97 - TRAFFIC CONTROL", [
    "CONTROL CALLS REAL SHIPS IN AND OUT OF THE BAYS ON THE BAND. STAY CLOSE TO A STATION AND LISTEN.",
  ]],
  ["0.96 - FOUR MORE CARDS", [
    "AN OLD PROBE STILL TALKING, THE LANTERN SHIPS, A STRANDED LINER, A SURVEY CREW'S CAIRN.",
  ]],
  ["0.95 - MORE VOICES", [
    "THE CROWD, THE TANNOY, THE CREW, THE PASSENGERS AND THE SHIP HAVE MORE TO SAY ABOUT EVERYTHING THAT'S NEW.",
  ]],
  ["0.94 - DOCS", [
    "THE README AND THE PLAYER'S GUIDE COVER EVERYTHING FROM THE ROSTER TO THE BORDER.",
  ]],
  ["0.93 - MORE WONDERS", [
    "THE LOOM, THE CLOCK AND THE CHOIR: THREE NEW KINDS OF VAST THING FOR NEW GALAXIES, WITH THEIR OWN LOOKS AND SOUNDS.",
  ]],
  ["0.92 - LOST AND FOUND", [
    "THE CAT SLIPS OUT ON THE PROMENADE. FIND HER BEFORE YOU BOARD, OR SHE WAITS FOR YOU, SMUG. THE BAND TALKS ABOUT THE WEEK.",
  ]],
  ["0.91 - PICTURES WANTED", [
    "STATIONS POST PICTURE JOBS: A WONDER, A WORLD FROM ORBIT. F7 IN THE RIGHT PLACE, THEN BRING IT BACK.",
  ]],
  ["0.90 - THE CONVOY", [
    "THREE SLOW HAULERS FORM ON YOUR STERN. KEEP THEM CLOSE, TAKE THEM TO ANY GATE, JUMP. THEY PAY ON THE OTHER SIDE.",
  ]],
  ["0.89 - HANDBOOK PAGES", [
    "THE IN-GAME HANDBOOK COVERS LIFE ABOARD, THE POST, THE RACE, STAKES AND THE VOTE, THE BORDER, THE FLEET AND THE WIRE.",
  ]],
  ["0.88 - THE WEEK", [
    "W ON THE RECORD TAB: VOTES, THE BORDER, THE REGATTA, HOLDINGS, CHARTERS AND FLEET ON ONE PAGE.",
  ]],
  ["0.87 - THE RALLY", [
    "CONTESTED STATIONS POST A RALLY: SUPPLIES FROM ANYWHERE AT A PREMIUM, AND A BIG PUSH TO HOLD THE SYSTEM.",
  ]],
  ["0.86 - THE BORDER", [
    "ONE SEAM SYSTEM A WEEK IS CONTESTED. WHAT YOU LAND, VOTE AND BUY THERE PUSHES. MONDAY SETTLES IT, STATIONS AND ALL.",
  ]],
  ["0.85 - SECOND STORIES", [
    "EVERY ROLE HAS TWO PERSONAL STORIES NOW. WHICH ONE YOUR CREW CARRY DEPENDS ON WHO THEY ARE.",
  ]],
  ["0.84 - FAVOURS", [
    "ASK A FRIEND IN THE LOUNGE IF THERE'S ANYTHING YOU CAN CARRY. NO FEE. A LETTER AND A GIFT LATER, AND A CAPTAIN WHO REMEMBERS.",
  ]],
  ["0.83 - NOTES AT THE WONDERS", [
    "WITHIN SIGHT OF A WONDER, LEAVE ONE LINE FOR WHOEVER COMES NEXT. THEY'LL READ IT ON THE BAND, WITH YOUR CALL SIGN.",
  ]],
  ["0.82 - MAYDAYS ON THE WIRE", [
    "RUN DRY IN THE REAL GALAXY AND YOUR MAYDAY GOES ON THE WIRE. ANOTHER PILOT CAN FIND YOU AND PASS FUEL. FUEL RATS, THIS WAY.",
  ]],
  ["0.81 - HOLDING SHORT", [
    "DOCK BEHIND TRAFFIC AND CONTROL HOLDS YOU SHORT OF THE BAY, THEN CALLS YOU IN.",
  ]],
  ["0.80 - FLEET AT WORK", [
    "W ON A PARKED HULL PUTS HER TO WORK ON YOUR BEST KNOWN RUN WITH A HIRED CREW. RELEASE HER AND SHE COMES BACK.",
  ]],
  ["0.79 - A TRADE OF THEIR OWN", [
    "CREW AT THE TOP OF THEIR TRADE PICK A SPECIALTY WHEN YOU TALK ABOARD. ONE EACH, FOR GOOD. IT SHOWS IN THE NUMBERS.",
  ]],
  ["0.78 - HANDBOOK", [
    "THE CONTROLS SCREEN CATCHES UP ON EVERYTHING NEW. THE TANNOY CHIMES, MESS CALL BLIPS.",
  ]],
  ["0.77 - THE VOTE", [
    "EVERY FACTION PUTS ONE QUESTION TO ITS CAPTAINS A WEEK. Y OR N ON THE NEWS TAB. WHAT PASSES SHAPES THE LANES.",
  ]],
  ["0.76 - STAKES", [
    "I ON THE MARKET TAB BUYS A SHARE IN THE STATION. EVERY DOCKING THERE PAYS A DIVIDEND. THE CROWD KNOWS AN OWNER.",
  ]],
  ["0.75 - THE REGATTA", [
    "FINISH A RACE AND YOU'RE ENTERED: THREE COURSES AT THREE STATIONS, THE LAST FIFTEEN UNDER PAR. WIN AND YOU'RE THE CHAMPION.",
  ]],
  ["0.74 - SALVAGE ON THE WIRE", [
    "IN THE REAL GALAXY, LOST SHIPS GO ON THE WIRE. OTHER PILOTS FIND YOUR WRECK; YOU FIND THEIRS, WITH SALVAGE ABOARD.",
  ]],
  ["0.73 - WHAT THE VOID KEEPS", [
    "LOSE YOUR SHIP AND ITS WRECK STAYS WHERE IT FELL, UNDER ITS NAME, WITH HALF THE HOLD. THE LOST GO ON THE WALL.",
  ]],
  ["0.72 - THE GUESTBOOK", [
    "PASSENGERS SIGN THE GUESTBOOK ON THE WAY OUT. THE HAPPY ONES COME BACK AND ASK FOR YOU BY NAME. P ON THE RECORD TAB.",
  ]],
  ["0.71 - GHOSTS ON THE LANES", [
    "IN THE REAL GALAXY, PILOTS WHO POSTED FROM YOUR SYSTEM LATELY HAVE THEIR SHIPS OUT HERE TOO. THEY HAIL ONCE.",
  ]],
  ["0.70 - PASSAGE", [
    "L ON THE SHIPS TAB: TAKE A LINER TO YOUR OTHER PARKED SHIP. A FARE A JUMP, HOURS PASS, THIS ONE STAYS HERE.",
  ]],
  ["0.69 - THE BAND", [
    "E AT THE COMMS ARRAY ABOARD: THE SERIAL, THE NEWS AND THE WIRE, WITH THE CREW LISTENING IN THE HATCHWAY.",
  ]],
  ["0.68 - STATION HOURS", [
    "EVERY STATION KEEPS ITS OWN CLOCK. NIGHT SHIFT DIMS THE PROMENADE, AND THE TANNOY HAS THINGS TO SAY.",
  ]],
  ["0.67 - CARDS AFTER WATCH", [
    "C BESIDE ANY CREW MEMBER: A HAND OF CARDS FOR MATCHSTICKS OR A ROUND. THE COOK'S MEAL IS BETTER THAN YOURS.",
  ]],
  ["0.66 - A NAME ON THE LANES", [
    "DO ONE THING MORE THAN ANYTHING ELSE AND THE LANES NAME YOU FOR IT. CONTROL, FRIENDS, THE CROWD AND THE CREW ALL USE IT.",
  ]],
  ["0.65 - RITES OF PASSAGE", [
    "A WEDDING ON THE BRIDGE, A BIRTH ON YOUR DECK, A PASSING BY THE VIEWPORT, AND TWO OF YOUR OWN ASKING YOU TO DO THE HONOURS.",
  ]],
  ["0.64 - THE POST", [
    "EVERY CIVIL STATION HAS A MAIL BAG FOR THE NEXT SHIP OUT. NO HOLD SPACE, SMALL PAY, AND SOMETIMES A LETTER IS FOR YOU.",
  ]],
  ["0.63 - WINDOWS AND BAYS", [
    "V ABOARD: LOOK OUT OF YOUR OWN SHIP. YOUR SHIP AND YOUR PARKED HULLS SIT IN THE PROMENADE BAYS.",
  ]],
  ["0.62 - THE COURSE RECORD", [
    "EVERY RING COURSE HAS A RECORD HOLDER. BEAT THEM AND THE BAR HEARS. IN THE REAL GALAXY YOUR TIMES GO TO THE WIRE.",
  ]],
  ["0.61 - WATCHES", [
    "HALF THE CREW ON WATCH AT THEIR POSTS, HALF OFF. PASSENGERS WALK THE DECK AND QUESTION THE CREW, WHO ANSWER IN CHARACTER.",
  ]],
  ["0.60 - THE RING RACE", [
    "ENTER FROM ANY LOUNGE, LAUNCH, AND FLY SIX RINGS ROUND THE STATION AGAINST THE CLOCK. PRIZE MONEY, PAR, YOUR BEST TIME.",
  ]],
  ["0.59 - CONCOURSE GOSSIP", [
    "THE CROWD ON A STATION PROMENADE TALK ABOUT THE WORLD, AND ABOUT YOU. STAND CLOSE AND LISTEN.",
  ]],
  ["0.58 - CORRIDOR TALK", [
    "THE CREW TALK TO EACH OTHER ABOARD, WALK THE DECK DOOR TO DOOR, AND GATHER AT THE GALLEY AT MESS CALL. EAT WITH THEM.",
  ]],
  ["0.57 - ENCOUNTERS", [
    "TEN NEW CARDS ON THE LANES AND THE GROUND, NONE OF THEM FIGHTS: A BUOY, A LOST DRONE, A BIRTHDAY, A HOT POOL, AND MORE.",
  ]],
  ["0.56 - THE ROSTER", [
    "R ABOARD OR IN THE LOUNGE: THE WHOLE CREW ON ONE PAGE, WITH MORALE, LOYALTY, SKILL PROGRESS AND A BONUS ON ENTER.",
  ]],
  ["0.55 - ODDS AND ENDS", [
    "EACH HULL CLASS HAS ITS OWN VOICE. RETIREMENTS REACH THE WIRE. THE GALAXY MAP HAS A LEGEND.",
  ]],
  ["0.54 - REGULARS", [
    "STATIONS COUNT YOUR DOCKINGS. BULLETINS MENTION YOU, PASSENGERS LEAVE REVIEWS, THE YARD GIVES REGULARS A RATE.",
  ]],
  ["0.53 - PASSENGERS UNDERFOOT", [
    "PASSENGERS STRETCH THEIR LEGS ABOARD: THE SEAT, THE GALLEY, THE BRIDGE. TALK TO WHOEVER YOU'RE BESIDE.",
  ]],
  ["0.52 - LORE", [
    "EVERY SYSTEM AND EVERY WORLD HAS A LINE OF HISTORY NOW. THE CHART READS IT ON ARRIVAL.",
  ]],
  ["0.51 - MORE OF EVERYTHING", [
    "TEN SERIALS, TWENTY-FOUR ENCOUNTERS, NINE KINDS OF WONDER, MORE TRAITS, A HAMMOCK AND A MURAL FOR THE DECK.",
  ]],
  ["0.50 - THE CHRONICLE ROOM", [
    "READ YOUR WHOLE CHRONICLE IN-GAME: C ON THE RECORD TAB, THE TITLE SCREEN, OR THE PAUSE MENU.",
  ]],
  ["0.49 - MUSIC AND SLOTS", [
    "THE HUM CHANGES FOR YOUR WAYSTATION, THE ARK AND THE WONDERS. SAVE SLOTS TELL THE STORY SO FAR.",
  ]],
  ["0.48 - OTHER KEEPERS", [
    "IN THE REAL GALAXY, LIGHTS OTHER PILOTS HAVE PLANTED SHOW ON YOUR CHART. YOURS SHOW ON THEIRS.",
  ]],
  ["0.47 - COMFORT", [
    "SETTINGS FOR THE COMMS BAND AND THE SHIP'S VOICE. V HIDES THE GALAXY MAP OVERLAYS. TOUCH GETS PAUSE AND LOG.",
  ]],
  ["0.46 - SMALL KINDNESSES", [
    "THE CROSSING RETURNS TO A KEPT LIGHT. THE CAT BRINGS THINGS UP FROM THE HOLD. THE WALL KEEPS ALL THREE CAMPAIGNS.",
  ]],
  ["0.45 - THE LEDGER", [
    "B ON THE RECORD TAB: WHERE THE MONEY CAME FROM AND WHERE IT WENT, LIFETIME, BY SOURCE.",
  ]],
  ["0.44 - COMPANY", [
    "CREW WALK THE DECK. PASSENGERS ASK FOR DETOURS TO WONDERS FOR 40% MORE. OLD SHIPMATES WRITE.",
  ]],
  ["0.43 - PLACES WITH DETAIL", [
    "CRATES IN THE HOLD, CREW BELONGINGS BY THEIR BUNKS, LUGGAGE BY THE SEAT, PROMENADES DRESSED FOR THEIR TRADE.",
  ]],
  ["0.42 - TOWN PROJECTS", [
    "A TOWN'S FOREMAN TAKES FUNDING: A SCHOOL, A CLINIC, A SECOND PAD, A CHAPEL. GROWTH, EFFECTS, AND A BUILDING TO SEE.",
  ]],
  ["0.41 - THE KEEPER", [
    "A THIRD CAMPAIGN: A DYING LIGHTHOUSE, ITS KEEPER'S LOG, WHAT THE LIGHT SAW, AND WHOSE LIGHT IT IS.",
  ]],
  ["0.40 - QUIET MOMENTS", [
    "ESC IN FLIGHT PAUSES THE GALAXY: SAVE, SETTINGS, THE HANDBOOK, OR HOME. PULSARS TICK; THE CATHEDRAL HUMS.",
  ]],
  ["0.39 - FACES", [
    "A SENATOR, AN HEIR AND A SINGER WANT SHIPS NOW AND THEN. LAND THEM HAPPY OR SOUR AND THE GALAXY HEARS.",
    "THE PROMENADE CROWD MATCHES THE DAY: STALLS, MOURNERS, PICKETS, REVELLERS.",
  ]],
  ["0.38 - CREW ARCS", [
    "CREW WHO TRUST YOU ASK FOR SOMETHING BIGGER: THEIR OWN STORY, THREE BEATS LONG, ADVANCED BY REAL PLAY.",
  ]],
  ["0.37 - SHARED SKY", [
    "IN THE REAL GALAXY, THE FIRST PILOT TO LOG A WONDER PUTS THEIR NAME ON EVERYONE'S CHART. L OPENS THE COMMS LOG.",
  ]],
  ["0.36 - SECOND HOUR", [
    "FLIGHT SCHOOL HAS THREE MORE LESSONS: THE LOUNGE, THE PROMENADE, A FARE OR A RESCUE. THE CAT PURRS. LETTERS CHIME.",
  ]],
  ["0.35 - RHYTHMS", [
    "THE WEEK HAS A SHAPE: FOUNDERS' DAY, THE LONG SILENCE, LANTERN NIGHT, MARKET DAY, REMEMBRANCE, YARD DAY, OPEN LANES.",
    "USED HULLS CARRY A HISTORY. A LIT BEACON EASES PIRACY IN ITS SYSTEM.",
  ]],
  ["0.34 - BELONGING", [
    "ASK A FRIEND IN THE LOUNGE TO RIDE ALONG. CALL A STATION HOME. DONATE RELICS TO A MUSEUM WITH YOUR NAME UNDER THE GLASS.",
  ]],
  ["0.33 - RIVALS", [
    "ONE OF THE REGULARS HAS IT IN FOR YOU: FARES TAKEN, SIGHTS LOGGED FIRST, ROUTES UNDERCUT. HELP THEM TWICE TO END IT.",
    "A HARBOURMASTER'S OFFICE ON THE PROMENADE KNOWS THE LANES, YOUR BERTH LOG AND YOUR CHARTERS.",
  ]],
  ["0.32 - HANDBOOK AND VOICE", [
    "A HANDBOOK ON THE TITLE SCREEN. THE SHIP SPEAKS ON THE BAND NOW AND THEN. A GREENHOUSE GROWS PROVISIONS.",
  ]],
  ["0.31 - THE WAYSTATION", [
    "TURN A LIT BEACON OR DEPOT INTO A WAYSTATION OF YOUR OWN: A TILL, A BAR THE REGULARS DRINK AT, A BUNK.",
  ]],
  ["0.30 - CONTACTS", [
    "THE LANES HAVE REGULARS. HELP ONE TWICE AND THEY'RE A FRIEND: HAILS, A SEAT IN THE LOUNGE, LETTERS WITH GIFTS.",
  ]],
  ["0.29 - APPROACH AND LAUNCH", [
    "DOCKING IS AN APPROACH NOW: CONTROL CLEARS A BAY AND THE SHIP GLIDES IN. LAUNCHES TOO. THE ARK CAN BE BOARDED.",
  ]],
  ["0.28 - WONDERS", [
    "EVERY GALAXY HAS LANDMARKS NOW: A RING, A PULSAR, AN ARK, A GLASS BELT, TWIN STARS. RUMOURS IN THE BARS POINT THE WAY.",
  ]],
  ["0.27 - CHARTERS", [
    "CHARTER A HAULER AT ANY SHIPYARD TO RUN YOUR BEST KNOWN ROUTE WHILE YOU FLY. 60% OF THE MARGIN IS YOURS.",
  ]],
  ["0.26 - SETTLEMENTS GROW", [
    "OUTPOSTS GROW ON YOUR TRADE AND WORK: 100 MAKES A TOWN, 250 A CITY, WITH YOUR NAME ON THE PLAQUE.",
  ]],
  ["0.25 - SHIPMATES", [
    "CREW MAKE FRIENDS AND ENEMIES. FEUDS DRAG MORALE DOWN UNTIL YOU SIT THEM DOWN WITH A BOTTLE.",
    "A CLINIC ON THE PROMENADE. X ON THE RECORD TAB EXPORTS YOUR WHOLE CHRONICLE AS TEXT.",
  ]],
  ["0.24 - KEEPSAKES", [
    "F7 TAKES A POSTCARD. FURNISH THE DECK AT ANY SHIPYARD: A PLANT, A RUG, A JUKEBOX, A VIEWPORT, A SHELF.",
    "THE LANES REMEMBER: THE COMMS BAND TALKS ABOUT YOUR SHIP BY NAME ONCE IT HAS EARNED IT.",
  ]],
  ["0.23 - SERIALS", [
    "GALNET RUNS SERIALS NOW: STORIES IN PARTS, KEPT ON THE NEWS TAB, ENDING IN A CONTRACT, A PREMIUM OR A RECRUIT.",
  ]],
  ["0.22 - LIFE ON THE DECK", [
    "CREW LEARN BY DOING: REPAIRS, KILLS, JUMPS AND PATIENTS COUNT TOWARD THE NEXT SKILL.",
    "REST A WHILE AT ANY SHIPYARD. A SHIP'S CAT FROM THE HOLD OR AN AGRI YARD. ION STORMS THAT BEACONS SEE THROUGH.",
  ]],
  ["0.21 - LEGACY", [
    "RETIRE THE CAPTAIN AT THE WALL OF RECORD. A CREW MEMBER TAKES THE CHAIR, OR THE YARD FINDS A NEW NAME.",
    "THE SHIP, ITS WALL, ITS CREW, YOUR STRUCTURES AND EVERYONE YOU FLEW WITH STAY. THE OLD CAPTAIN WALKS THE PROMENADE.",
  ]],
  ["0.20 - THE LIGHTHOUSE", [
    "SQUADRON TREATIES ON THE BASE TAB: PACTS SIGNED BY BOTH SIDES, RIVALRIES DECLARED BY ONE.",
    "SIX MORE ENCOUNTERS. THE TITLE SCREEN TELLS THE STORY SO FAR. THE SHIPS TAB SHOWS YOUR PAINT.",
    "WALK THE DECK AND MEET YOUR OWN PEOPLE: CREW ON LEAVE AND SHIPMATES WHO RETIRED HERE.",
    "BEACON AND FUEL DEPOT KITS AT ANY SHIPYARD. PLANT THEM IN A DEAD SYSTEM WITH E.",
    "BEACONS PULL TRAFFIC AND COLLECT TOLLS; JUMPS THROUGH A LIT SYSTEM COST A FIFTH LESS. DEPOTS SELL YOUR FUEL.",
    "RAIDERS WEAR STRUCTURES DOWN. BRING SPARE PARTS, EMPTY THE TILL, KEEP THE LIGHT ON.",
  ]],
  ["0.19 - THE LINER TRADE", [
    "FARES WAIT IN EVERY STATION LOUNGE: VIPS, TOURISTS, REFUGEES, COURIERS, FUGITIVES. CABINS CARRY THREE.",
    "PASSENGERS HAVE MOODS. BRING WHAT THEY ASK FOR, KEEP THE HULL WHOLE, DON'T DAWDLE. PAY RUNS 60-120%.",
    "TOURISTS BOOK A SIGHT: A WORLD, THE DRIFTERS, A COMET, A FESTIVAL. EVERY EXTRA SIGHT PAYS MORE.",
  ]],
  ["0.18 - A LIFE ABOARD", [
    "CREW HAVE LIVES: SHORE LEAVE (THEY KEEP THEIR BERTH), LISTS FOR THE GALLEY, LETTERS CARRIED HOME.",
    "PEOPLE GET SICK. MED SUPPLIES CURE IT AT THE NEXT DOCK; A MEDIC HALVES THE LAY-UP.",
    "AFTER THIRTY DOCKINGS SOMEONE MAY WANT TO GO HOME. HOW YOU PART MATTERS TO THE REST.",
    "THE SHIP WEARS WITH HOURS AND JUMPS. YARD SERVICE AT ANY SHIPYARD; THE BERTH LOG REMEMBERS.",
  ]],
  ["0.17 - A LIVING GALAXY", [
    "A RESCUER CAREER LADDER BUILT FROM LIVES SAVED, REPAIRS, TOWS AND CRISES BROKEN.",
    "COMETS SEED RICH BELTS, SOLAR FLARES COOK HULLS, FESTIVAL WEEKS PAY TOURISTS DOUBLE, DOCK STRIKES DOUBLE YARD PRICES.",
    "BAR RUMOURS POINT AT REAL TROUBLE. A CAPTAIN'S LOG (L ON RECORD) AND A CODEX (C ON SURVEY).",
    "THE COMMS BAND IS ALIVE: CONTROL, HAULERS, PATROLS. SHIPS ARRIVE AND LEAVE THROUGH THE GATES AND DOCK FOR REAL.",
    "CORSAIRS TURNING UP WHILE YOU FIX A FREIGHTER IS A RISK OF ROUGH SPACE NOW, NOT A RULE.",
    "STATIONS HAVE PROFILES AND LOCAL BULLETINS. HAULERS LAUNCH FROM BAYS. NAV LIGHTS BLINK. ENGINES GLOW.",
    "VOID DRIFTERS: SOMETHING LIVES NEAR THE GAS GIANTS. HOLD V NEARBY AND LOG IT.",
    "FACTION ENVOYS: AMNESTIES FOR SALE, CHARTERS AT 75 STANDING (+15% CONTRACT PAY), EMBARGOES BELOW -40.",
    "YOUR SHIP REMEMBERS: A WALL OF RECORD BY THE AIRLOCK (E TO READ), PLAQUES FOR DEEDS, SCORCH WHILE THE HULL IS HURT.",
    "WIND SOUNDS LIKE THE WORLD IT'S ON. STATION PA CHIMES, GATE CRACKS, DRIFTER SONG.",
    "THE MISSING CONVOY: A SECOND CAMPAIGN FOR PILOTS A SYNDICATE TRUSTS. THE TRUTH IS WORTH DIFFERENT THINGS TO DIFFERENT PEOPLE.",
    "OUTPOSTS AND CITIES HAVE MOODS. A LINE ON ARRIVAL TELLS YOU WHAT KIND OF DAY IT IS DOWN THERE.",
    "CREW TALK TO EACH OTHER ABOARD, AND YOU CAN HEAR HOW THEY FEEL ABOUT THE SHIP.",
    "OUTPOSTS HAVE NEEDS (+40% AT THE TRADE DESK) AND A FOREMAN AT THE SURVEY OFFICE WITH GROUND JOBS AND A PLANT TO FIX.",
    "SETTLEMENTS LIGHT UP ON THE NIGHT SIDE FROM ORBIT. AT THE MARKET, ENTER SELLS WHAT YOU HOLD AND BUYS ONLY WHEN YOU HOLD NONE. SHIFT TRADES IN BULK.",
  ]],
  ["0.16 - THE SIGNAL", [
    "A CAMPAIGN: SOMETHING UNDER THE STARLIGHT IS COUNTING. SEVEN STAGES ACROSS THE GALAXY, A FIGHT OR A PARLEY AT THE END.",
    "ENCOUNTERS: FOURTEEN CHOICE CARDS IN FLIGHT AND ON THE GROUND. PODS, SMUGGLERS, CUSTOMS, GHOSTS, WILDLIFE, METEORITES.",
    "CHOICES HAVE CONSEQUENCES: CREW, CARGO, STANDING, MATERIALS, DAMAGE, AND DEBTS PAID BACK AT YOUR NEXT DOCK.",
    "CREW ASK FOR THINGS WHEN YOU DOCK; LOYALTY SURVIVES A BAD WEEK. STAKE UP TO THREE HOMESTEAD CLAIMS (H AT THE LANDER).",
    "MAYDAYS: BOARD A DISABLED FREIGHTER AND FIX IT, OR SEND YOUR ENGINEER ACROSS WHILE YOU HOLD OFF THE CORSAIRS.",
    "OR TOW IT INTO DOCK, OR TAKE THE SURVIVORS ABOARD. STATIONS POST ENGINEERING TENDERS AND CALL CRISES THAT PAY 2.5X.",
    "MEDICS MATTER: FREIGHTERS CALL IN CASUALTIES. STANDING ORDERS PAY MORE WITH EVERY SHIPMENT.",
  ]],
  ["0.15 - SYNDICATES AND TRADE ROUTES", [
    "FOUR AI SYNDICATES PER GALAXY (ALWAYS MARKED AI): BASES WITH CONVOYS, RAIDERS IN RIVAL SPACE, RIVALRY IN THE NEWS.",
    "CONTRACTS AT THEIR BASES BUILD STANDING: AFFILIATES BUY LIKE ALLIES, PARTNERS GET +10% ON WANTED GOODS.",
    "EVERY BASE WANTS THREE GOODS A WEEK AT +30%; SALES FEED ITS TREASURY AND YOUR RUNS DRAW ON THE GALAXY MAP.",
    "DIPLOMACY: RELATIONS DRIFT AND ANSWER TO YOUR CONTRACTS. ALLIANCES SHARE PERKS; DEEP FEUDS BECOME WARS YOU CAN JOIN.",
    "A ROUT TAKES THE LOSER'S BASE AS A HOLDING; THEY FALL BACK TO A PARTNER STATION. HOLDINGS TRADE LIKE HOME BASES.",
    "SQUADRONS WITH A BASE CAN DECLARE FOR A SIDE IN A SYNDICATE WAR: SPOILS TO THE TREASURY, OR A GRUDGE.",
    "THE HUM IS OFF BY DEFAULT NOW: H OR SETTINGS TURNS IT ON.",
  ]],
  ["0.14 - SQUADRON BASES", [
    "A SQUADRON CAN POOL CREDITS AND BUY A CIVILIAN STATION: SHARED VAULT, HALF-PRICE SERVICES,",
    "UPGRADES (DEFENSE GRID, FUEL DEPOT, MARKET STAKE, DEEP VAULT). UNDEFENDED BASES DRAW RAIDERS.",
    "TWO NEW HULLS: ALBATROSS EXPLORER AND OX MINING BARGE. LOST WARS CAN CHANGE A SYSTEM'S FLAG.",
    "WEEKLY BASE CONTRACT AND SQUADRON BOUNTY PAY THE TREASURY. /S TALKS ON YOUR SQUADRON CHANNEL ANYWHERE.",
    "THREE SAVE SLOTS FROM THE TITLE SCREEN, EACH WITH ITS OWN CLOUD CODE. O IN SHIPS PAINTS YOUR TRIM.",
    "MAYDAY: A PILOT UNDER 25% HULL HAILS THE SYSTEM AND OTHERS GET A MARKER. ROVER SUSPENSION AND BATTERY BLUEPRINTS.",
  ]],
  ["0.13 - OTHER PILOTS", [
    "PILOTS IN THE SAME SYSTEM SEE EACH OTHER'S SHIPS. T OPENS THE SYSTEM CHANNEL.",
    "/GIVE AND /PAY HAND OVER GOODS AND CREDITS. KILLS NEAR A WINGMATE ARE SHARED.",
    "SQUADRONS: A SHARED TAG THAT RANKS TOGETHER. THE BEST-STANDING SQUADRON BECOMES",
    "A FACTION'S PATRON. THE GALAXY MAP SHOWS WHERE PILOTS ARE. OPT OUT IN SETTINGS.",
  ]],
  ["0.12 - GROUNDSIDE", [
    "L FROM ORBIT DROPS A ROVER ON ANY REGION: BIOMES, STORMS, NIGHT, OUTCROPS, FLORA,",
    "PROBES, WRECKS. OUTPOSTS, CITIES AND RUINS ARE DOORS ON THE GROUND.",
    "GROUND CONTRACTS ON MISSION BOARDS. A CODEX OF SPECIES AND BIOMES.",
  ]],
  ["0.11 - THE QUIET PROFESSIONS", [
    "TWELVE SHIP MODULES, FUEL SCOOPING, CRUISE (J) AND AUTOPILOT (N), EXPLORATION DATA",
    "AND CAREER RANKS, RARE GOODS, MATERIALS AND AN ENGINEER BAY, CORE MINING WITH",
    "SEISMIC CHARGES, FLEET PARKING, PERMIT SPACE, BLACK MARKETS, WEEKLY COMMUNITY GOAL.",
  ]],
  ["0.10 - DEPTH", [
    "ACHIEVEMENTS, DAILY CONTRACT, HARDCORE MODE, FIVE FACTION ARCS, KEY REBINDING,",
    "MOUSE TURRET AIM, TORPEDOES, PIRATE CAPTAINS, A NEW STARSHIP HUM.",
  ]],
];

// Long notes wrap to the screen width instead of running off the right edge
const WRAP_AT = 92;
function wrapLine(l: string): string[] {
  const out: string[] = []; let cur = "";
  for (const wd of l.split(" ")) { if ((cur + " " + wd).trim().length > WRAP_AT && cur) { out.push(cur); cur = wd; } else cur = cur ? cur + " " + wd : wd; }
  if (cur) out.push(cur);
  return out;
}
// each entry reflows as one paragraph, so a long line never leaves an orphan word on its own row
const WRAPPED: [string, string[]][] = NOTES.map(([t, lines]) => [t, wrapLine(lines.join(" "))]);

export class WhatsNewScene implements Scene {
  touchMode = "menu" as const;
  scroll = 0;
  enter(): void { this.scroll = 0; saveSettings({ whatsNewSeen: typeof __APP_VERSION__ === "string" ? __APP_VERSION__ : "?" }); }
  update(g: Game, dt: number): void {
    void dt;
    if (g.input.wasPressed("Escape") || g.input.wasPressed("Enter") || g.input.mousePressed) { g.setScene("title"); return; }
    const total = WRAPPED.reduce((a, [, lines]) => a + 9 + lines.length * 8 + 6, 0);
    const max = Math.max(0, total - (VH - 44));
    if (g.input.wasPressed("ArrowDown")) this.scroll = Math.min(max, this.scroll + 24);
    if (g.input.wasPressed("ArrowUp")) this.scroll = Math.max(0, this.scroll - 24);
    if (g.input.wheel) this.scroll = Math.max(0, Math.min(max, this.scroll + g.input.wheel * 24));
  }
  draw(g: Game, ctx: CanvasRenderingContext2D): void {
    void g;
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, VH);
    ctx.save(); ctx.beginPath(); ctx.rect(0, 18, VW, VH - 34); ctx.clip();
    let y = 24 - this.scroll;
    for (const [title, lines] of WRAPPED) {
      if (y > VH) break;
      if (y + 9 + lines.length * 8 > 18) {
        drawText(ctx, title, 12, y, PAL.ui);
        lines.forEach((l, i) => drawText(ctx, l, 12, y + 9 + i * 8, PAL.grey));
      }
      y += 9 + lines.length * 8 + 6;
    }
    ctx.restore();
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, 18); ctx.fillRect(0, VH - 16, VW, 16);
    drawText(ctx, "WHAT'S NEW - UP/DOWN OR WHEEL TO SCROLL", 12, 8, PAL.white);
    drawText(ctx, "ESC BACK", VW - textWidth("ESC BACK") - 12, 8, PAL.greyDark);
    drawText(ctx, "FULL ROADMAP: GITHUB.COM/AES256AFRO/FARSPACE", 12, VH - 12, PAL.greyDark);
  }
}
