// What's new: a short changelog for returning pilots, reachable from the title.

import { Game, Scene, VW, VH } from "../game";
import { drawText, textWidth } from "../gfx/font";
import { PAL } from "../gfx/palette";
import { saveSettings } from "../core/settings";

const NOTES: [string, string[]][] = [
  ["0.56 TO 0.128 - THE LONG DAY", [
    "SEVENTY-FOUR MILESTONES IN ONE SITTING: THE ROSTER, CORRIDOR TALK, THE RING RACE AND REGATTA, THE POST, STAKES,",
    "THE VOTE, THE BORDER, FLEET AT WORK, THE LINER, MAYDAYS AND NOTES ON THE WIRE, CONVOYS, FAMILY, AND THE REST BELOW.",
  ]],
  ["0.128 - THE DOCK-HAND", [
    "SOMEONE MEETS YOUR SHIP AT THE CLAMP AND HAS ALREADY LOOKED HER OVER: THE HOLE, THE RATTLE, THE FUMES, THE FULL",
    "HOLD, THE GREEN FARES, THE CAT AT THE AIRLOCK. E BY YOUR BAY FOR THEIR OPINION. REGULARS GET A SMALL JOB ON THE HOUSE",
    "ONCE A WEEK: A PLATE, A SPLASH IN THE TANK, OR GREASE ON WHAT RATTLES.",
  ]],
  ["0.127 - STATION HOURS MATTER", [
    "THE HOUR SETS THE RATE. NIGHT SHIFT: HULL WORK AND SERVICING 15% OVER. EARLY SHIFT, BEFORE ELEVEN: 10% UNDER.",
    "FUEL IS FUEL. THE LOUNGE FILLS AFTER DARK; NIGHT CONTROL ASKS YOU TO KEEP IT QUIET. THE NEXT PORT KEEPS ITS OWN CLOCK.",
    "THE SHIPYARD LIST SCROLLS WITH THE CURSOR NOW, AND LONG NOTES SIT ON THE INFO LINE INSTEAD OF OVER THE ROW.",
  ]],
  ["0.126 - BERTH NEIGHBOURS", [
    "CAPTAINS YOU KNOW WALK THE PROMENADE WHEN THEIR SHIP IS IN THE BAYS: HOME-PORT CAPTAINS YOU HAVE MET,",
    "FRIENDS PASSING THROUGH, THE RIVAL WHENEVER THEY ARE HOME. E FOR A WORD; ONCE A WEEK A FRIEND SETTLES A ROUND",
    "OR HANDS OVER A SPARE. THEIR HULL SITS IN THE FAR BAY AND THE TANNOY SAYS WHO IS IN.",
  ]],
  ["0.125 - PAGING", [
    "THE TANNOY KNOWS WHO IS BERTHED. MAIL WAITING, THE CAT LEFT BEHIND, FAMILY ON THE PROMENADE, A CONSIGNMENT",
    "THE HARBOURMASTER IS EXPECTING, A HULL TRAILING SOMETHING, A TANK ON FUMES: THE STATION SAYS SO, TWICE.",
    "LONG CALLS WRAP ON THE PROMENADE AND SCROLL THROUGH A WINDOW ON THE SERVICES SCREEN. NOTHING IS CUT SHORT.",
  ]],
  ["0.124 - CONVOY MANNERS", [
    "DOCK WITH A CONVOY ON YOUR STERN OR A RACE RUNNING AND THEY LET YOU GO WITH A WORD, NOT A SILENT VANISH.",
  ]],
  ["0.123 - PICTURES IN THE MUSEUM", [
    "A PICTURE JOB TURNED IN AT A RESEARCH STATION HANGS IN ITS MUSEUM WITH YOUR NAME UNDER IT.",
  ]],
  ["0.122 - KEEPSAKES II", [
    "THE CHRONICLE CARRIES THE GUESTBOOK. THE WALL OF RECORD LISTS YOUR RING TIMES. THE ROSTER TOTALS THE WAGES.",
  ]],
  ["0.121 - HANDBOOK INDEX", [
    "THE HANDBOOK'S HEADER LISTS ITS SECTIONS. THE SHIP HAS OPINIONS ABOUT THE VOTE.",
  ]],
  ["0.120 - TIDY II", [
    "THE TITLE SUMMARY CARRIES YOUR NAME ON THE LANES. THE HANDBOOK KNOWS THE PACER, THE WAGER AND CONVOYS ON THE BOARD.",
  ]],
  ["0.119 - CONVOY ON THE BOARD", [
    "STATIONS POST CONVOYS ON THE MISSIONS BOARD. ACCEPT ONE AND IT FORMS ON YOUR STERN WHEN YOU LAUNCH.",
  ]],
  ["0.118 - ODDS AND ENDS II", [
    "THE CHAMPION GETS TALKED ABOUT. FARES BOARD IMPRESSED WHERE YOU HOLD THE RINGS. THE ROSTER MARKS FAMILIES MET.",
  ]],
  ["0.117 - PEOPLE IN THE CODEX", [
    "THE CODEX COUNTS THE PEOPLE: CAPTAINS MET, NOTABLES CARRIED, OLD SHIPMATES, FAMILIES VISITED.",
  ]],
  ["0.116 - THE LANES REPORT", [
    "YOUR HOME PORT'S HARBOUR OFFICE WRITES EACH NEW WEEK: THE BORDER, YOUR HOLDINGS, YOUR BERTH.",
  ]],
  ["0.115 - THE MARSHAL'S CHALLENGE", [
    "A MARSHAL'S TENDER MAY OFFER A WAGER: THE NEXT RUN UNDER PAR PAYS DOUBLE. BIG SHAREHOLDERS GET A BAY OF THEIR OWN.",
  ]],
  ["0.114 - UNREAD", [
    "THE TITLE MARKS WHAT'S NEW WHEN THERE'S SOMETHING YOU HAVEN'T READ.",
  ]],
  ["0.113 - THE GRAND COURSE", [
    "THE REGATTA'S LAST COURSE IS EIGHT WIDE RINGS. THE CONVOY LEAD TALKS ON THE WAY TO THE GATE.",
  ]],
  ["0.112 - CHEQUES IN THE POST", [
    "YOUR OTHER HOLDINGS PAY A QUARTER DIVIDEND WHEREVER YOU DOCK. THE GUESTBOOK IS READABLE AT THE PASSENGER SEAT.",
  ]],
  ["0.111 - THE PACER", [
    "A GHOST RUNS THE RINGS AT THE RECORD PACE SO YOU CAN SEE IF YOU'RE UP OR DOWN. THE FIRST DOCK OF A WEEK ANNOUNCES THE WEEK.",
  ]],
  ["0.110 - TIDY", [
    "THE HANDBOOK COVERS SCRAPPING AND WRITING BACK; THE SHIP HAS A WORD ABOUT FAMILY AND LETTERS.",
  ]],
  ["0.109 - GUIDE CONTENTS", [
    "THE PLAYER'S GUIDE HAS A GROUPED CONTENTS. BORDER RESULTS YOU PUSHED FOR GO TO THE WIRE.",
  ]],
  ["0.108 - LOOSE ENDS", [
    "RECORD HOLDERS WRITE WHEN YOU BEAT THEM. RACE DAY PAYS HALF AGAIN. TOURISTS WANT A COPY OF THE POSTCARD.",
  ]],
  ["0.107 - WRITING BACK", [
    "R ON THE NEWS TAB WRITES BACK TO YOUR LATEST LETTER. CAPTAINS REMEMBER WHO ANSWERS.",
  ]],
  ["0.106 - DEEDS AND SLOTS", [
    "FIVE MORE DEEDS ON THE RECORD, AND THE SAVE SLOTS SHOW YOUR NAME ON THE LANES.",
  ]],
  ["0.105 - THE CHRONICLE'S WEEK", [
    "THE CHRONICLE TELLS THE WEEK: YOUR VOTES, THE BORDER, YOUR HOLDINGS AND TIMES, AS PROSE.",
  ]],
  ["0.104 - SMALL TOUCHES", [
    "SPECIALTIES IN THE CHRONICLE, THE BORDER ON THE BAND, A HARDCORE LOSS LEAVES A WRECK ON THE CHART, YOUR NAME ON POSTCARDS.",
  ]],
  ["0.103 - CALLS AND COURSES", [
    "THE GALAXY MAP LISTS THIS WEEK'S CALLS FOR HELP. N ON THE MARKET PLOTS A COURSE TO THE BEST KNOWN SELL.",
  ]],
  ["0.102 - HUM", [
    "THE TANNOY SPEAKS WHILE YOU TRADE. THE SHIP CALLS THE WATCH CHANGE. THE LOUNGE IS ON THE BAND.",
  ]],
  ["0.101 - SCRAP", [
    "X ON A PARKED HULL SELLS HER TO THE YARD FOR SCRAP. CREDITS TODAY; NO GETTING HER BACK.",
    "THE TITLE TICKER SHOWS THIS WEEK'S CONTESTED SYSTEM AND HOW IT STANDS.",
  ]],
  ["0.100 - FAMILY", [
    "DOCK AT A CREW MEMBER'S HOME PORT AND SOMEONE OF THEIRS IS ON THE PROMENADE. TALK TO THEM.",
  ]],
  ["0.99 - GENTLE LANES", [
    "SETTINGS HAS THE LANES: GENTLE, NORMAL OR ROUGH. HALF THE CORSAIRS IF YOU'D RATHER TRADE, TALK AND RACE.",
  ]],
  ["0.98 - PORTS REMEMBER YOU", [
    "THE HARBOURMASTER'S OFFICE HAS YOU ON FILE: DOCKINGS, YOUR STAKE, FARES LANDED, YOUR VOTE, YOUR RING TIMES.",
  ]],
  ["0.97 - TRAFFIC CONTROL", [
    "CONTROL CALLS REAL SHIPS IN AND OUT OF THE BAYS ON THE BAND. STAY CLOSE TO A STATION AND LISTEN.",
  ]],
  ["0.96 - FOUR MORE CARDS", [
    "AN OLD PROBE STILL TALKING, THE LANTERN SHIPS, A STRANDED LINER, A SURVEY CREW'S CAIRN.",
  ]],
  ["0.95 - MORE VOICES", [
    "THE CROWD, THE TANNOY, THE CREW, THE PASSENGERS AND THE SHIP HAVE MORE TO SAY ABOUT EVERYTHING THAT'S NEW.",
  ]],
  ["0.94 - DOCS", [
    "THE README AND THE PLAYER'S GUIDE COVER EVERYTHING FROM THE ROSTER TO THE BORDER.",
  ]],
  ["0.93 - MORE WONDERS", [
    "THE LOOM, THE CLOCK AND THE CHOIR: THREE NEW KINDS OF VAST THING FOR NEW GALAXIES, WITH THEIR OWN LOOKS AND SOUNDS.",
  ]],
  ["0.92 - LOST AND FOUND", [
    "THE CAT SLIPS OUT ON THE PROMENADE. FIND HER BEFORE YOU BOARD, OR SHE WAITS FOR YOU, SMUG. THE BAND TALKS ABOUT THE WEEK.",
  ]],
  ["0.91 - PICTURES WANTED", [
    "STATIONS POST PICTURE JOBS: A WONDER, A WORLD FROM ORBIT. F7 IN THE RIGHT PLACE, THEN BRING IT BACK.",
  ]],
  ["0.90 - THE CONVOY", [
    "THREE SLOW HAULERS FORM ON YOUR STERN. KEEP THEM CLOSE, TAKE THEM TO ANY GATE, JUMP. THEY PAY ON THE OTHER SIDE.",
  ]],
  ["0.89 - HANDBOOK PAGES", [
    "THE IN-GAME HANDBOOK COVERS LIFE ABOARD, THE POST, THE RACE, STAKES AND THE VOTE, THE BORDER, THE FLEET AND THE WIRE.",
  ]],
  ["0.88 - THE WEEK", [
    "W ON THE RECORD TAB: VOTES, THE BORDER, THE REGATTA, HOLDINGS, CHARTERS AND FLEET ON ONE PAGE.",
  ]],
  ["0.87 - THE RALLY", [
    "CONTESTED STATIONS POST A RALLY: SUPPLIES FROM ANYWHERE AT A PREMIUM, AND A BIG PUSH TO HOLD THE SYSTEM.",
  ]],
  ["0.86 - THE BORDER", [
    "ONE SEAM SYSTEM A WEEK IS CONTESTED. WHAT YOU LAND, VOTE AND BUY THERE PUSHES. MONDAY SETTLES IT, STATIONS AND ALL.",
  ]],
  ["0.85 - SECOND STORIES", [
    "EVERY ROLE HAS TWO PERSONAL STORIES NOW. WHICH ONE YOUR CREW CARRY DEPENDS ON WHO THEY ARE.",
  ]],
  ["0.84 - FAVOURS", [
    "ASK A FRIEND IN THE LOUNGE IF THERE'S ANYTHING YOU CAN CARRY. NO FEE. A LETTER AND A GIFT LATER, AND A CAPTAIN WHO REMEMBERS.",
  ]],
  ["0.83 - NOTES AT THE WONDERS", [
    "WITHIN SIGHT OF A WONDER, LEAVE ONE LINE FOR WHOEVER COMES NEXT. THEY'LL READ IT ON THE BAND, WITH YOUR CALL SIGN.",
  ]],
  ["0.82 - MAYDAYS ON THE WIRE", [
    "RUN DRY IN THE REAL GALAXY AND YOUR MAYDAY GOES ON THE WIRE. ANOTHER PILOT CAN FIND YOU AND PASS FUEL. FUEL RATS, THIS WAY.",
  ]],
  ["0.81 - HOLDING SHORT", [
    "DOCK BEHIND TRAFFIC AND CONTROL HOLDS YOU SHORT OF THE BAY, THEN CALLS YOU IN.",
  ]],
  ["0.80 - FLEET AT WORK", [
    "W ON A PARKED HULL PUTS HER TO WORK ON YOUR BEST KNOWN RUN WITH A HIRED CREW. RELEASE HER AND SHE COMES BACK.",
  ]],
  ["0.79 - A TRADE OF THEIR OWN", [
    "CREW AT THE TOP OF THEIR TRADE PICK A SPECIALTY WHEN YOU TALK ABOARD. ONE EACH, FOR GOOD. IT SHOWS IN THE NUMBERS.",
  ]],
  ["0.78 - HANDBOOK", [
    "THE CONTROLS SCREEN CATCHES UP ON EVERYTHING NEW. THE TANNOY CHIMES, MESS CALL BLIPS.",
  ]],
  ["0.77 - THE VOTE", [
    "EVERY FACTION PUTS ONE QUESTION TO ITS CAPTAINS A WEEK. Y OR N ON THE NEWS TAB. WHAT PASSES SHAPES THE LANES.",
  ]],
  ["0.76 - STAKES", [
    "I ON THE MARKET TAB BUYS A SHARE IN THE STATION. EVERY DOCKING THERE PAYS A DIVIDEND. THE CROWD KNOWS AN OWNER.",
  ]],
  ["0.75 - THE REGATTA", [
    "FINISH A RACE AND YOU'RE ENTERED: THREE COURSES AT THREE STATIONS, THE LAST FIFTEEN UNDER PAR. WIN AND YOU'RE THE CHAMPION.",
  ]],
  ["0.74 - SALVAGE ON THE WIRE", [
    "IN THE REAL GALAXY, LOST SHIPS GO ON THE WIRE. OTHER PILOTS FIND YOUR WRECK; YOU FIND THEIRS, WITH SALVAGE ABOARD.",
  ]],
  ["0.73 - WHAT THE VOID KEEPS", [
    "LOSE YOUR SHIP AND ITS WRECK STAYS WHERE IT FELL, UNDER ITS NAME, WITH HALF THE HOLD. THE LOST GO ON THE WALL.",
  ]],
  ["0.72 - THE GUESTBOOK", [
    "PASSENGERS SIGN THE GUESTBOOK ON THE WAY OUT. THE HAPPY ONES COME BACK AND ASK FOR YOU BY NAME. P ON THE RECORD TAB.",
  ]],
  ["0.71 - GHOSTS ON THE LANES", [
    "IN THE REAL GALAXY, PILOTS WHO POSTED FROM YOUR SYSTEM LATELY HAVE THEIR SHIPS OUT HERE TOO. THEY HAIL ONCE.",
  ]],
  ["0.70 - PASSAGE", [
    "L ON THE SHIPS TAB: TAKE A LINER TO YOUR OTHER PARKED SHIP. A FARE A JUMP, HOURS PASS, THIS ONE STAYS HERE.",
  ]],
  ["0.69 - THE BAND", [
    "E AT THE COMMS ARRAY ABOARD: THE SERIAL, THE NEWS AND THE WIRE, WITH THE CREW LISTENING IN THE HATCHWAY.",
  ]],
  ["0.68 - STATION HOURS", [
    "EVERY STATION KEEPS ITS OWN CLOCK. NIGHT SHIFT DIMS THE PROMENADE, AND THE TANNOY HAS THINGS TO SAY.",
  ]],
  ["0.67 - CARDS AFTER WATCH", [
    "C BESIDE ANY CREW MEMBER: A HAND OF CARDS FOR MATCHSTICKS OR A ROUND. THE COOK'S MEAL IS BETTER THAN YOURS.",
  ]],
  ["0.66 - A NAME ON THE LANES", [
    "DO ONE THING MORE THAN ANYTHING ELSE AND THE LANES NAME YOU FOR IT. CONTROL, FRIENDS, THE CROWD AND THE CREW ALL USE IT.",
  ]],
  ["0.65 - RITES OF PASSAGE", [
    "A WEDDING ON THE BRIDGE, A BIRTH ON YOUR DECK, A PASSING BY THE VIEWPORT, AND TWO OF YOUR OWN ASKING YOU TO DO THE HONOURS.",
  ]],
  ["0.64 - THE POST", [
    "EVERY CIVIL STATION HAS A MAIL BAG FOR THE NEXT SHIP OUT. NO HOLD SPACE, SMALL PAY, AND SOMETIMES A LETTER IS FOR YOU.",
  ]],
  ["0.63 - WINDOWS AND BAYS", [
    "V ABOARD: LOOK OUT OF YOUR OWN SHIP. YOUR SHIP AND YOUR PARKED HULLS SIT IN THE PROMENADE BAYS.",
  ]],
  ["0.62 - THE COURSE RECORD", [
    "EVERY RING COURSE HAS A RECORD HOLDER. BEAT THEM AND THE BAR HEARS. IN THE REAL GALAXY YOUR TIMES GO TO THE WIRE.",
  ]],
  ["0.61 - WATCHES", [
    "HALF THE CREW ON WATCH AT THEIR POSTS, HALF OFF. PASSENGERS WALK THE DECK AND QUESTION THE CREW, WHO ANSWER IN CHARACTER.",
  ]],
  ["0.60 - THE RING RACE", [
    "ENTER FROM ANY LOUNGE, LAUNCH, AND FLY SIX RINGS ROUND THE STATION AGAINST THE CLOCK. PRIZE MONEY, PAR, YOUR BEST TIME.",
  ]],
  ["0.59 - CONCOURSE GOSSIP", [
    "THE CROWD ON A STATION PROMENADE TALK ABOUT THE WORLD, AND ABOUT YOU. STAND CLOSE AND LISTEN.",
  ]],
  ["0.58 - CORRIDOR TALK", [
    "THE CREW TALK TO EACH OTHER ABOARD, WALK THE DECK DOOR TO DOOR, AND GATHER AT THE GALLEY AT MESS CALL. EAT WITH THEM.",
  ]],
  ["0.57 - ENCOUNTERS", [
    "TEN NEW CARDS ON THE LANES AND THE GROUND, NONE OF THEM FIGHTS: A BUOY, A LOST DRONE, A BIRTHDAY, A HOT POOL, AND MORE.",
  ]],
  ["0.56 - THE ROSTER", [
    "R ABOARD OR IN THE LOUNGE: THE WHOLE CREW ON ONE PAGE, WITH MORALE, LOYALTY, SKILL PROGRESS AND A BONUS ON ENTER.",
  ]],
  ["0.55 - ODDS AND ENDS", [
    "EACH HULL CLASS HAS ITS OWN VOICE. RETIREMENTS REACH THE WIRE. THE GALAXY MAP HAS A LEGEND.",
  ]],
  ["0.54 - REGULARS", [
    "STATIONS COUNT YOUR DOCKINGS. BULLETINS MENTION YOU, PASSENGERS LEAVE REVIEWS, THE YARD GIVES REGULARS A RATE.",
  ]],
  ["0.53 - PASSENGERS UNDERFOOT", [
    "PASSENGERS STRETCH THEIR LEGS ABOARD: THE SEAT, THE GALLEY, THE BRIDGE. TALK TO WHOEVER YOU'RE BESIDE.",
  ]],
  ["0.52 - LORE", [
    "EVERY SYSTEM AND EVERY WORLD HAS A LINE OF HISTORY NOW. THE CHART READS IT ON ARRIVAL.",
  ]],
  ["0.51 - MORE OF EVERYTHING", [
    "TEN SERIALS, TWENTY-FOUR ENCOUNTERS, NINE KINDS OF WONDER, MORE TRAITS, A HAMMOCK AND A MURAL FOR THE DECK.",
  ]],
  ["0.50 - THE CHRONICLE ROOM", [
    "READ YOUR WHOLE CHRONICLE IN-GAME: C ON THE RECORD TAB, THE TITLE SCREEN, OR THE PAUSE MENU.",
  ]],
  ["0.49 - MUSIC AND SLOTS", [
    "THE HUM CHANGES FOR YOUR WAYSTATION, THE ARK AND THE WONDERS. SAVE SLOTS TELL THE STORY SO FAR.",
  ]],
  ["0.48 - OTHER KEEPERS", [
    "IN THE REAL GALAXY, LIGHTS OTHER PILOTS HAVE PLANTED SHOW ON YOUR CHART. YOURS SHOW ON THEIRS.",
  ]],
  ["0.47 - COMFORT", [
    "SETTINGS FOR THE COMMS BAND AND THE SHIP'S VOICE. V HIDES THE GALAXY MAP OVERLAYS. TOUCH GETS PAUSE AND LOG.",
  ]],
  ["0.46 - SMALL KINDNESSES", [
    "THE CROSSING RETURNS TO A KEPT LIGHT. THE CAT BRINGS THINGS UP FROM THE HOLD. THE WALL KEEPS ALL THREE CAMPAIGNS.",
  ]],
  ["0.45 - THE LEDGER", [
    "B ON THE RECORD TAB: WHERE THE MONEY CAME FROM AND WHERE IT WENT, LIFETIME, BY SOURCE.",
  ]],
  ["0.44 - COMPANY", [
    "CREW WALK THE DECK. PASSENGERS ASK FOR DETOURS TO WONDERS FOR 40% MORE. OLD SHIPMATES WRITE.",
  ]],
  ["0.43 - PLACES WITH DETAIL", [
    "CRATES IN THE HOLD, CREW BELONGINGS BY THEIR BUNKS, LUGGAGE BY THE SEAT, PROMENADES DRESSED FOR THEIR TRADE.",
  ]],
  ["0.42 - TOWN PROJECTS", [
    "A TOWN'S FOREMAN TAKES FUNDING: A SCHOOL, A CLINIC, A SECOND PAD, A CHAPEL. GROWTH, EFFECTS, AND A BUILDING TO SEE.",
  ]],
  ["0.41 - THE KEEPER", [
    "A THIRD CAMPAIGN: A DYING LIGHTHOUSE, ITS KEEPER'S LOG, WHAT THE LIGHT SAW, AND WHOSE LIGHT IT IS.",
  ]],
  ["0.40 - QUIET MOMENTS", [
    "ESC IN FLIGHT PAUSES THE GALAXY: SAVE, SETTINGS, THE HANDBOOK, OR HOME. PULSARS TICK; THE CATHEDRAL HUMS.",
  ]],
  ["0.39 - FACES", [
    "A SENATOR, AN HEIR AND A SINGER WANT SHIPS NOW AND THEN. LAND THEM HAPPY OR SOUR AND THE GALAXY HEARS.",
    "THE PROMENADE CROWD MATCHES THE DAY: STALLS, MOURNERS, PICKETS, REVELLERS.",
  ]],
  ["0.38 - CREW ARCS", [
    "CREW WHO TRUST YOU ASK FOR SOMETHING BIGGER: THEIR OWN STORY, THREE BEATS LONG, ADVANCED BY REAL PLAY.",
  ]],
  ["0.37 - SHARED SKY", [
    "IN THE REAL GALAXY, THE FIRST PILOT TO LOG A WONDER PUTS THEIR NAME ON EVERYONE'S CHART. L OPENS THE COMMS LOG.",
  ]],
  ["0.36 - SECOND HOUR", [
    "FLIGHT SCHOOL HAS THREE MORE LESSONS: THE LOUNGE, THE PROMENADE, A FARE OR A RESCUE. THE CAT PURRS. LETTERS CHIME.",
  ]],
  ["0.35 - RHYTHMS", [
    "THE WEEK HAS A SHAPE: FOUNDERS' DAY, THE LONG SILENCE, LANTERN NIGHT, MARKET DAY, REMEMBRANCE, YARD DAY, OPEN LANES.",
    "USED HULLS CARRY A HISTORY. A LIT BEACON EASES PIRACY IN ITS SYSTEM.",
  ]],
  ["0.34 - BELONGING", [
    "ASK A FRIEND IN THE LOUNGE TO RIDE ALONG. CALL A STATION HOME. DONATE RELICS TO A MUSEUM WITH YOUR NAME UNDER THE GLASS.",
  ]],
  ["0.33 - RIVALS", [
    "ONE OF THE REGULARS HAS IT IN FOR YOU: FARES TAKEN, SIGHTS LOGGED FIRST, ROUTES UNDERCUT. HELP THEM TWICE TO END IT.",
    "A HARBOURMASTER'S OFFICE ON THE PROMENADE KNOWS THE LANES, YOUR BERTH LOG AND YOUR CHARTERS.",
  ]],
  ["0.32 - HANDBOOK AND VOICE", [
    "A HANDBOOK ON THE TITLE SCREEN. THE SHIP SPEAKS ON THE BAND NOW AND THEN. A GREENHOUSE GROWS PROVISIONS.",
  ]],
  ["0.31 - THE WAYSTATION", [
    "TURN A LIT BEACON OR DEPOT INTO A WAYSTATION OF YOUR OWN: A TILL, A BAR THE REGULARS DRINK AT, A BUNK.",
  ]],
  ["0.30 - CONTACTS", [
    "THE LANES HAVE REGULARS. HELP ONE TWICE AND THEY'RE A FRIEND: HAILS, A SEAT IN THE LOUNGE, LETTERS WITH GIFTS.",
  ]],
  ["0.29 - APPROACH AND LAUNCH", [
    "DOCKING IS AN APPROACH NOW: CONTROL CLEARS A BAY AND THE SHIP GLIDES IN. LAUNCHES TOO. THE ARK CAN BE BOARDED.",
  ]],
  ["0.28 - WONDERS", [
    "EVERY GALAXY HAS LANDMARKS NOW: A RING, A PULSAR, AN ARK, A GLASS BELT, TWIN STARS. RUMOURS IN THE BARS POINT THE WAY.",
  ]],
  ["0.27 - CHARTERS", [
    "CHARTER A HAULER AT ANY SHIPYARD TO RUN YOUR BEST KNOWN ROUTE WHILE YOU FLY. 60% OF THE MARGIN IS YOURS.",
  ]],
  ["0.26 - SETTLEMENTS GROW", [
    "OUTPOSTS GROW ON YOUR TRADE AND WORK: 100 MAKES A TOWN, 250 A CITY, WITH YOUR NAME ON THE PLAQUE.",
  ]],
  ["0.25 - SHIPMATES", [
    "CREW MAKE FRIENDS AND ENEMIES. FEUDS DRAG MORALE DOWN UNTIL YOU SIT THEM DOWN WITH A BOTTLE.",
    "A CLINIC ON THE PROMENADE. X ON THE RECORD TAB EXPORTS YOUR WHOLE CHRONICLE AS TEXT.",
  ]],
  ["0.24 - KEEPSAKES", [
    "F7 TAKES A POSTCARD. FURNISH THE DECK AT ANY SHIPYARD: A PLANT, A RUG, A JUKEBOX, A VIEWPORT, A SHELF.",
    "THE LANES REMEMBER: THE COMMS BAND TALKS ABOUT YOUR SHIP BY NAME ONCE IT HAS EARNED IT.",
  ]],
  ["0.23 - SERIALS", [
    "GALNET RUNS SERIALS NOW: STORIES IN PARTS, KEPT ON THE NEWS TAB, ENDING IN A CONTRACT, A PREMIUM OR A RECRUIT.",
  ]],
  ["0.22 - LIFE ON THE DECK", [
    "CREW LEARN BY DOING: REPAIRS, KILLS, JUMPS AND PATIENTS COUNT TOWARD THE NEXT SKILL.",
    "REST A WHILE AT ANY SHIPYARD. A SHIP'S CAT FROM THE HOLD OR AN AGRI YARD. ION STORMS THAT BEACONS SEE THROUGH.",
  ]],
  ["0.21 - LEGACY", [
    "RETIRE THE CAPTAIN AT THE WALL OF RECORD. A CREW MEMBER TAKES THE CHAIR, OR THE YARD FINDS A NEW NAME.",
    "THE SHIP, ITS WALL, ITS CREW, YOUR STRUCTURES AND EVERYONE YOU FLEW WITH STAY. THE OLD CAPTAIN WALKS THE PROMENADE.",
  ]],
  ["0.20 - THE LIGHTHOUSE", [
    "SQUADRON TREATIES ON THE BASE TAB: PACTS SIGNED BY BOTH SIDES, RIVALRIES DECLARED BY ONE.",
    "SIX MORE ENCOUNTERS. THE TITLE SCREEN TELLS THE STORY SO FAR. THE SHIPS TAB SHOWS YOUR PAINT.",
    "WALK THE DECK AND MEET YOUR OWN PEOPLE: CREW ON LEAVE AND SHIPMATES WHO RETIRED HERE.",
    "BEACON AND FUEL DEPOT KITS AT ANY SHIPYARD. PLANT THEM IN A DEAD SYSTEM WITH E.",
    "BEACONS PULL TRAFFIC AND COLLECT TOLLS; JUMPS THROUGH A LIT SYSTEM COST A FIFTH LESS. DEPOTS SELL YOUR FUEL.",
    "RAIDERS WEAR STRUCTURES DOWN. BRING SPARE PARTS, EMPTY THE TILL, KEEP THE LIGHT ON.",
  ]],
  ["0.19 - THE LINER TRADE", [
    "FARES WAIT IN EVERY STATION LOUNGE: VIPS, TOURISTS, REFUGEES, COURIERS, FUGITIVES. CABINS CARRY THREE.",
    "PASSENGERS HAVE MOODS. BRING WHAT THEY ASK FOR, KEEP THE HULL WHOLE, DON'T DAWDLE. PAY RUNS 60-120%.",
    "TOURISTS BOOK A SIGHT: A WORLD, THE DRIFTERS, A COMET, A FESTIVAL. EVERY EXTRA SIGHT PAYS MORE.",
  ]],
  ["0.18 - A LIFE ABOARD", [
    "CREW HAVE LIVES: SHORE LEAVE (THEY KEEP THEIR BERTH), LISTS FOR THE GALLEY, LETTERS CARRIED HOME.",
    "PEOPLE GET SICK. MED SUPPLIES CURE IT AT THE NEXT DOCK; A MEDIC HALVES THE LAY-UP.",
    "AFTER THIRTY DOCKINGS SOMEONE MAY WANT TO GO HOME. HOW YOU PART MATTERS TO THE REST.",
    "THE SHIP WEARS WITH HOURS AND JUMPS. YARD SERVICE AT ANY SHIPYARD; THE BERTH LOG REMEMBERS.",
  ]],
  ["0.17 - A LIVING GALAXY", [
    "A RESCUER CAREER LADDER BUILT FROM LIVES SAVED, REPAIRS, TOWS AND CRISES BROKEN.",
    "COMETS SEED RICH BELTS, SOLAR FLARES COOK HULLS, FESTIVAL WEEKS PAY TOURISTS DOUBLE, DOCK STRIKES DOUBLE YARD PRICES.",
    "BAR RUMOURS POINT AT REAL TROUBLE. A CAPTAIN'S LOG (L ON RECORD) AND A CODEX (C ON SURVEY).",
    "THE COMMS BAND IS ALIVE: CONTROL, HAULERS, PATROLS. SHIPS ARRIVE AND LEAVE THROUGH THE GATES AND DOCK FOR REAL.",
    "CORSAIRS TURNING UP WHILE YOU FIX A FREIGHTER IS A RISK OF ROUGH SPACE NOW, NOT A RULE.",
    "STATIONS HAVE PROFILES AND LOCAL BULLETINS. HAULERS LAUNCH FROM BAYS. NAV LIGHTS BLINK. ENGINES GLOW.",
    "VOID DRIFTERS: SOMETHING LIVES NEAR THE GAS GIANTS. HOLD V NEARBY AND LOG IT.",
    "FACTION ENVOYS: AMNESTIES FOR SALE, CHARTERS AT 75 STANDING (+15% CONTRACT PAY), EMBARGOES BELOW -40.",
    "YOUR SHIP REMEMBERS: A WALL OF RECORD BY THE AIRLOCK (E TO READ), PLAQUES FOR DEEDS, SCORCH WHILE THE HULL IS HURT.",
    "WIND SOUNDS LIKE THE WORLD IT'S ON. STATION PA CHIMES, GATE CRACKS, DRIFTER SONG.",
    "THE MISSING CONVOY: A SECOND CAMPAIGN FOR PILOTS A SYNDICATE TRUSTS. THE TRUTH IS WORTH DIFFERENT THINGS TO DIFFERENT PEOPLE.",
    "OUTPOSTS AND CITIES HAVE MOODS. A LINE ON ARRIVAL TELLS YOU WHAT KIND OF DAY IT IS DOWN THERE.",
    "CREW TALK TO EACH OTHER ABOARD, AND YOU CAN HEAR HOW THEY FEEL ABOUT THE SHIP.",
    "OUTPOSTS HAVE NEEDS (+40% AT THE TRADE DESK) AND A FOREMAN AT THE SURVEY OFFICE WITH GROUND JOBS AND A PLANT TO FIX.",
    "SETTLEMENTS LIGHT UP ON THE NIGHT SIDE FROM ORBIT. AT THE MARKET, ENTER SELLS WHAT YOU HOLD AND BUYS ONLY WHEN YOU HOLD NONE. SHIFT TRADES IN BULK.",
  ]],
  ["0.16 - THE SIGNAL", [
    "A CAMPAIGN: SOMETHING UNDER THE STARLIGHT IS COUNTING. SEVEN STAGES ACROSS THE GALAXY, A FIGHT OR A PARLEY AT THE END.",
    "ENCOUNTERS: FOURTEEN CHOICE CARDS IN FLIGHT AND ON THE GROUND. PODS, SMUGGLERS, CUSTOMS, GHOSTS, WILDLIFE, METEORITES.",
    "CHOICES HAVE CONSEQUENCES: CREW, CARGO, STANDING, MATERIALS, DAMAGE, AND DEBTS PAID BACK AT YOUR NEXT DOCK.",
    "CREW ASK FOR THINGS WHEN YOU DOCK; LOYALTY SURVIVES A BAD WEEK. STAKE UP TO THREE HOMESTEAD CLAIMS (H AT THE LANDER).",
    "MAYDAYS: BOARD A DISABLED FREIGHTER AND FIX IT, OR SEND YOUR ENGINEER ACROSS WHILE YOU HOLD OFF THE CORSAIRS.",
    "OR TOW IT INTO DOCK, OR TAKE THE SURVIVORS ABOARD. STATIONS POST ENGINEERING TENDERS AND CALL CRISES THAT PAY 2.5X.",
    "MEDICS MATTER: FREIGHTERS CALL IN CASUALTIES. STANDING ORDERS PAY MORE WITH EVERY SHIPMENT.",
  ]],
  ["0.15 - SYNDICATES AND TRADE ROUTES", [
    "FOUR AI SYNDICATES PER GALAXY (ALWAYS MARKED AI): BASES WITH CONVOYS, RAIDERS IN RIVAL SPACE, RIVALRY IN THE NEWS.",
    "CONTRACTS AT THEIR BASES BUILD STANDING: AFFILIATES BUY LIKE ALLIES, PARTNERS GET +10% ON WANTED GOODS.",
    "EVERY BASE WANTS THREE GOODS A WEEK AT +30%; SALES FEED ITS TREASURY AND YOUR RUNS DRAW ON THE GALAXY MAP.",
    "DIPLOMACY: RELATIONS DRIFT AND ANSWER TO YOUR CONTRACTS. ALLIANCES SHARE PERKS; DEEP FEUDS BECOME WARS YOU CAN JOIN.",
    "A ROUT TAKES THE LOSER'S BASE AS A HOLDING; THEY FALL BACK TO A PARTNER STATION. HOLDINGS TRADE LIKE HOME BASES.",
    "SQUADRONS WITH A BASE CAN DECLARE FOR A SIDE IN A SYNDICATE WAR: SPOILS TO THE TREASURY, OR A GRUDGE.",
    "THE HUM IS OFF BY DEFAULT NOW: H OR SETTINGS TURNS IT ON.",
  ]],
  ["0.14 - SQUADRON BASES", [
    "A SQUADRON CAN POOL CREDITS AND BUY A CIVILIAN STATION: SHARED VAULT, HALF-PRICE SERVICES,",
    "UPGRADES (DEFENSE GRID, FUEL DEPOT, MARKET STAKE, DEEP VAULT). UNDEFENDED BASES DRAW RAIDERS.",
    "TWO NEW HULLS: ALBATROSS EXPLORER AND OX MINING BARGE. LOST WARS CAN CHANGE A SYSTEM'S FLAG.",
    "WEEKLY BASE CONTRACT AND SQUADRON BOUNTY PAY THE TREASURY. /S TALKS ON YOUR SQUADRON CHANNEL ANYWHERE.",
    "THREE SAVE SLOTS FROM THE TITLE SCREEN, EACH WITH ITS OWN CLOUD CODE. O IN SHIPS PAINTS YOUR TRIM.",
    "MAYDAY: A PILOT UNDER 25% HULL HAILS THE SYSTEM AND OTHERS GET A MARKER. ROVER SUSPENSION AND BATTERY BLUEPRINTS.",
  ]],
  ["0.13 - OTHER PILOTS", [
    "PILOTS IN THE SAME SYSTEM SEE EACH OTHER'S SHIPS. T OPENS THE SYSTEM CHANNEL.",
    "/GIVE AND /PAY HAND OVER GOODS AND CREDITS. KILLS NEAR A WINGMATE ARE SHARED.",
    "SQUADRONS: A SHARED TAG THAT RANKS TOGETHER. THE BEST-STANDING SQUADRON BECOMES",
    "A FACTION'S PATRON. THE GALAXY MAP SHOWS WHERE PILOTS ARE. OPT OUT IN SETTINGS.",
  ]],
  ["0.12 - GROUNDSIDE", [
    "L FROM ORBIT DROPS A ROVER ON ANY REGION: BIOMES, STORMS, NIGHT, OUTCROPS, FLORA,",
    "PROBES, WRECKS. OUTPOSTS, CITIES AND RUINS ARE DOORS ON THE GROUND.",
    "GROUND CONTRACTS ON MISSION BOARDS. A CODEX OF SPECIES AND BIOMES.",
  ]],
  ["0.11 - THE QUIET PROFESSIONS", [
    "TWELVE SHIP MODULES, FUEL SCOOPING, CRUISE (J) AND AUTOPILOT (N), EXPLORATION DATA",
    "AND CAREER RANKS, RARE GOODS, MATERIALS AND AN ENGINEER BAY, CORE MINING WITH",
    "SEISMIC CHARGES, FLEET PARKING, PERMIT SPACE, BLACK MARKETS, WEEKLY COMMUNITY GOAL.",
  ]],
  ["0.10 - DEPTH", [
    "ACHIEVEMENTS, DAILY CONTRACT, HARDCORE MODE, FIVE FACTION ARCS, KEY REBINDING,",
    "MOUSE TURRET AIM, TORPEDOES, PIRATE CAPTAINS, A NEW STARSHIP HUM.",
  ]],
];

// Long notes wrap to the screen width instead of running off the right edge
const WRAP_AT = 92;
function wrapLine(l: string): string[] {
  const out: string[] = []; let cur = "";
  for (const wd of l.split(" ")) { if ((cur + " " + wd).trim().length > WRAP_AT && cur) { out.push(cur); cur = wd; } else cur = cur ? cur + " " + wd : wd; }
  if (cur) out.push(cur);
  return out;
}
const WRAPPED: [string, string[]][] = NOTES.map(([t, lines]) => [t, lines.flatMap(wrapLine)]);

export class WhatsNewScene implements Scene {
  touchMode = "menu" as const;
  scroll = 0;
  enter(): void { this.scroll = 0; saveSettings({ whatsNewSeen: typeof __APP_VERSION__ === "string" ? __APP_VERSION__ : "?" }); }
  update(g: Game, dt: number): void {
    void dt;
    if (g.input.wasPressed("Escape") || g.input.wasPressed("Enter") || g.input.mousePressed) { g.setScene("title"); return; }
    const total = WRAPPED.reduce((a, [, lines]) => a + 9 + lines.length * 8 + 6, 0);
    const max = Math.max(0, total - (VH - 44));
    if (g.input.wasPressed("ArrowDown")) this.scroll = Math.min(max, this.scroll + 24);
    if (g.input.wasPressed("ArrowUp")) this.scroll = Math.max(0, this.scroll - 24);
    if (g.input.wheel) this.scroll = Math.max(0, Math.min(max, this.scroll + g.input.wheel * 24));
  }
  draw(g: Game, ctx: CanvasRenderingContext2D): void {
    void g;
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, VH);
    ctx.save(); ctx.beginPath(); ctx.rect(0, 18, VW, VH - 34); ctx.clip();
    let y = 24 - this.scroll;
    for (const [title, lines] of WRAPPED) {
      if (y > VH) break;
      if (y + 9 + lines.length * 8 > 18) {
        drawText(ctx, title, 12, y, PAL.ui);
        lines.forEach((l, i) => drawText(ctx, l, 12, y + 9 + i * 8, PAL.grey));
      }
      y += 9 + lines.length * 8 + 6;
    }
    ctx.restore();
    ctx.fillStyle = PAL.uiPanel; ctx.fillRect(0, 0, VW, 18); ctx.fillRect(0, VH - 16, VW, 16);
    drawText(ctx, "WHAT'S NEW - UP/DOWN OR WHEEL TO SCROLL", 12, 8, PAL.white);
    drawText(ctx, "ESC BACK", VW - textWidth("ESC BACK") - 12, 8, PAL.greyDark);
    drawText(ctx, "FULL ROADMAP: GITHUB.COM/AES256AFRO/FARSPACE", 12, VH - 12, PAL.greyDark);
  }
}
